project:
  type: website
  output-dir: docs
    
website:
  title: Lotterhos Lab Protocols
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    logo: img/Lotterhos_logo2.png
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "General"
        contents:
          - general_welcome.qmd 
          - general_expectations.qmd
          - general_GettingStarted.qmd
          - general_waste_clearing.qmd
          - general_ShippingHazMat.qmd
          - general_shared_equipment.qmd
          - general_reimbursement.qmd
          - general_receiving.qmd
          - general_purchasing.qmd
          - general_ordering.qmd
          - general_MVI-scope-camera.qmd
          - general_freezer.qmd
          - general_fedex_ship.qmd
          - general_creating_barcoded_labels.qmd
          - general_chemical_inventory.qmd
          - general_autoclave.qmd
      - section: "Professional Development"
        contents: 
          - profdev.qmd
          - profdev_ReducingCognitiveLoad.qmd
          - profdev_How-to-publish-a-paper.qmd
          - profdev_design.qmd
          - profdev_courses.qmd
      - section: "Molecular Protocols"
        contents:
          - molecprot_barcodesnindexes.qmd
          - molecprot_dnaextractionomega.qmd
          - molecprot_dnaextractionqiagen.qmd
          - molecprot_dnaextractionspartina.qmd
          - molecprot_gelelectrophoresis.qmd
          - molecprot_illuminalibraryprep.qmd
          - molecprot_qPCR-Libraryquant.qmd
          - molecprot_rnaextraction.qmd
          - molecprot_solutionrecipes.qmd
          - molecprot_etoh.qmd
          - molecprot_gonad_buffer.qmd
      - section: "Molecular Equipment"
        contents:
          - molecprot_take3dnaquantification.qmd
          - molecprot_picoGreenAssay.qmd
          - molecprot_magbeadwash.qmd
          - molecprot_tapestationlibrarycheck.qmd
          - molecprot_qPCRandBioRAD.qmd
          - molecprot_outdated.qmd
      - section: "Field and Sampling Protocols"
        contents:
          - field_collectsampdna.qmd
          - field_collectsamprna.qmd
          - field_conductivityloggers.qmd
          - field_fieldsafety_protocol.qmd
          - field_oystersampling.qmd
          - field_kayak.qmd
          - field_phloggers.qmd
          - field_Seatables.qmd
          - field_watersampling.qmd
      - section: "Coding Protocols"
        contents: 
          - code_bioinformatics.qmd
          - code_checksums.qmd
          - code_defiance.qmd
          - code_directoryorganization.qmd
          - code_githhubMarkdown.qmd
          - code_LearningToCode.qmd
          - code_pathAndAliasMod.qmd
          - code_pseudoparallel.qmd
          - code_setseeds.qmd
          - code_TroubleshootingCellprofiler.qmd
          - code_unixcommands.qmd
          - code_versioncontrol.qmd
          - code_quarto.qmd
      - section: "Discovery"
        contents:
          - discovery_slurmArrays.qmd
          - discovery_nonNEUpersonnel.qmd
          - discovery_integrated-development-environment.qmd
          - discovery_6-optimization.qmd
          - discovery_5-parallelization.qmd
          - discovery_4-examples.qmd
          - discovery_3-storage.qmd
          - discovery_2-globus.qmd
          - discovery_1a-OOD.qmd
          - discovery_1-gettingstarted.qmd
          
format:
  html:
    theme: [lumen, theme.scss]
    toc: true

editor: visual

execute:
  freeze: auto
