project:
  type: book

book:
  title: "lotterhos-lab-protocols"
  author: "Katie Lotterhos"
  date: "10/19/2022"
  chapters:
    - index.qmd

    - part: "General"
      chapters:
        - expectations.qmd 
        - welcome.qmd 
        - getting-started.qmd
        - freezer.qmd
        - autoclave.qmd
        - ordering-supplies.qmd
        - receiving-supplies.qmd
        - purchasing.qmd
        - reimbursement.qmd
        - mvi-scope-camera.qmd
        - barcoded-labels.qmd
        - shipping-haz-mats.qmd
        - fedex-shipping.qmd
        - lab-waste.qmd
        - chem-inventory.qmd
      
    - part: "Professional Development"
      chapters:
        - reducing-cog-load.qmd
        - how-to-publish.qmd
        - general-resources.qmd
        - design.qmd
        - courses.qmd
        
    - part: "Molecular Protocols"
      chapters: 
        - types-of-ethanol.qmd
        - solution-recipes.qmd
        - determining-barcodes.qmd
        - qiagen.qmd
        - omega.qmd
        - spartina.qmd
        - rna-extraction.qmd
        - gel-electrophoresis.qmd
        - illumina-library.qmd
        - library-quantification.qmd
        
    - part: "Molecular Equipment"
      chapters:
        - shared-equipment.qmd
        - take3-dna-quantification.qmd
        - picogreen-assay.qmd
        - magnetic-bead-wash.qmd
        - tapestation.qmd
        - qpcr-on-biorad.qmd
        - outdated-protocols.qmd
        
    - part: "Field and Sampling Protocols"
      chapters:
        - collecting-dna.qmd
        - collecting-rna.qmd
        - water-sampling.qmd
        - conductivity-loggers.qmd
        - ph-loggers.qmd
        - seatables.qmd
        - kayak.qmd
        - oyster-sampling.qmd
        - field-safety-protocols.qmd
        
    - part: "Coding Protocols"
      chapters: 
        - learning-to-code.qmd
        - bioinfo-resources.qmd
        - github-version-control.qmd
        - directory-organization.qmd
        - unix-commands.qmd
        - regular-expressions.qmd
        - setting-alias.qmd
        - setting-seeds.qmd
        - transferring-files.qmd
        - cellprofiler-install.qmd
        - defiance-cluster.qmd
        - pseudo-parallel.qmd
        - github-figures.qmd
        
    - part: "Discovery"
      chapters: 
        - discovery.qmd
        - open-on-demand.qmd
        - globus.qmd
        - storage.qmd
        - parallelization.qmd
        - optimization.qmd
        - example-scripts.qmd
        - vs-code-pycharm.qmd
        - non-nu-discovery.qmd
        - using-arrays.qmd
        
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

