# Learning to Code

------------------------------------------------------------------------

## Options for downloading programs

[Edit this page link](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/gh-pages/code_LearningToCode.md)

1.  You can download and install on your computer

2.  You can use NU's [Open On Demand](https://drk-lo.github.io/lotterhoslabprotocols/code_LearningToCode/ood.discovery.neu.edu) for R Studio, command line, and python, and more!

    -   To use OOD, you have to have an NU email, and have Discovery access (NU's HPC cluster).

        -   [Instructions to get Discovery access for non-NU people](https://drk-lo.github.io/lotterhoslabprotocols/discovery_nonNEUpersonnel/)

    -   Once you have Discovery Access, you can follow [these intructions](https://docs.google.com/document/d/1sJAnQXE8-r_4ssr5VfVv0oZKFrrrRFxspdxx2kNdaLI/edit#heading=h.61692qeq0wnf), but instead of the `course` dropdown menu, use the `Interactive Apps` dropdown to find the program you need

## **Learning R** {.unnumbered}

1.  [Follow the instructions for downloading R and R studio in this syllabus (if you scroll down)](https://docs.google.com/document/d/1-qm-gVOIb-k61PxlQvav_GZXgmZP4t7q1fjs4BN_Ov8/edit#heading=h.jl4d8sgkpjrk)

2.  Start with this [great introduction to R and R studio](https://rafalab.github.io/dsbook/getting-started.html) and data science with R. Start with the first 3 chapters.

3.  After you get a handle on R, start using `swirl`. It's an interactive learning environment [Visit this site for an overview of swirl](https://swirlstats.com/students.html) [Then visit this site for an overview of courses](https://github.com/swirldev/swirl_courses#swirl-courses)

I recommend starting with the "R programming E" course

    library(swirl)
    install_course("R programming E")
    swirl()

1.  After you finish the above steps, it's time to review what you know with your advisor and discuss the best way to build your skills based on your goals. Next steps may include:

    -   [Other swirl courses](https://swirlstats.com/scn/title.html)

    -   [More advanced chapters in R for data science](https://rafalab.github.io/dsbook/getting-started.html)

    -   [Software carpentry and Data Carpentry courses](https://carpentries.org/) Taking a course is great, but the course material is public and it's easy to learn from

# **Learning the command line** {.unnumbered}

1.  The first hurdle might be what kind of computer you have. If you have a Mac, use the Terminal. If you have a PC, google "use the command line on a PC". The command line functions (and how well they work) might vary a bit among platforms.

2.  Get started with Software Carpentry's [The Unix Shell](https://swcarpentry.github.io/shell-novice/)

3.  I also like the book `Practical Computing for Biologists` (a book you have to buy)

## **Learning Python** {.unnumbered}

1.  On a mac, I recommend downloading [Anaconda](https://www.anaconda.com/). I don't know about running python on a PC.

2.  This free python textbook is the best https://python-textbok.readthedocs.io/en/1.0/Python_Basics.html

3.  This is a great resource for learning python, but the courses are not free: (https://pythonforbiologists.com/)\[https://pythonforbiologists.com/\]

    -   In the menu, under training courses, there is a lot of options

    -   I bought the book "Introduction to Python for Biologists" and went through it myself

4.  Here are some [resources I have yet to vet](https://wiki.python.org/moin/BeginnersGuide/Programmers)

5. learning aspects of python based around Harry Potter examples (they changed names to avoid copyright problems). Note the GitHub page has link to blog posts that walk through the code. https://github.com/zotroneneis/magical_universe
Here is the podcast about this, lots of other cool topics too. https://talkpython.fm/episodes/show/186/100-days-of-python-in-a-magical-universe

## **Learning Bioinformatics** {.unnumbered}

1.  Vince Buffalo's [Bioinformatics Data Skills](https://vincebuffalo.com/book/)

## **Learning Machine Learning** {.unnumbered}

https://christophm.github.io/interpretable-ml-book/

https://www.fast.ai/

https://course.fast.ai/start_colab

## **Learning SLiM** {.unnumbered}

http://benhaller.com/workshops/workshops.html

## **Advanced concepts** {.unnumbered}

[Interactive vignettes for machine learning and stats](https://distill.pub/)

[Making beautiful networks](https://gephi.org/)

## **Making Maps in R** {.unnumbered}

[Data Carpentry Geospatial Materials](https://datacarpentry.org/organization-geospatial/) Introduction to raster and vector data

[GG ocean maps](https://mikkovihtakari.github.io/ggOceanMaps/articles/ggOceanMaps.html#advanced-use-1) beautiful ocean maps.

-   For shallow bathymetries, the default is not great. Scroll down to the advanced data and see "bathymetries" and how to set the depths you want. You save the raster file, then you have to do the same thing for your land data.

[Basic intro to maps in R](https://rpubs.com/kvistj/mapping)

[GG plot maps - molecular ecologist](https://www.molecularecologist.com/2016/07/01/making-maps-in-r-volume-2-ggplots/)

## **Other** {.unnumbered}

https://github.com/thais-neu/Thais-learning-code
