# Globus File Transfer

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/discovery_2-globus.qmd)

------------------------------------------------------------------------

-   Globus is a system for transferring files. The pros:

    -   It's fast

    -   If your connection gets interrupted, it automatically picks up where it left off

    -   It automatically checks that your files were not corrupted during the transfer

    -   Globus is already integrated with Discovery and our lab files.

    -   It makes transferring files among your laptop, your collaborator(s), and Discovery easy.

    -   A **Globus endpoint** is a folder on a computer that you want to transfer files to or from

    -   A **Globus Collection** is a folder on a computer that contains a collection of files. You may create several endpoints within a collection to share with specific people.

## **Getting started with Globus on Discovery** {.unnumbered}

-   Go to [globus.org](globus.org)

-   Click on "Login", from the dropdown list choose "Northeastern University", login with your NU credentials

-   Click on "File Manager" and the Search Icon. In the Search Box type "Northeastern". Choose "northeastern#discovery". This is your home directory on Discovery. Click on the Bookmark Icon to add this to your bookmarks.

-   Dr. Lotterhos will share through Globus the specific folders that you will have access to on the Discovery Lab Storage

## **Getting started with Globus on your laptop** {.unnumbered}

-   Download [Globus Connect Personal](https://www.globus.org/globus-connect-personal) for your laptop and follow the instructions to setup and configure your laptop as an endpoint

-   Make sure to save your setup key, you'll need it again to open the Globus App on your computer

-   If you get error messages, try restarting your Terminal

## **Transferring files in Globus** {.unnumbered}

-   Click on "File Manager"

-   In the upper right, click on the Double-Panel Icon. This will open two panels - choose the collections that you would like to transfer files between, and drag and drop!

-   can view other's scratch directories and copy files, but not edit

-   other users can view /research/lotterhos and edit/delete files

## **Sharing endpoints** {.unnumbered}

-   A **Globus endpoint** is a folder on a computer that you want to transfer files to or from. In Globus, click on the folder ("Collection") that you would like to allow file transfer to or from.

-   To let someone download files in that folder, give them access to "read" the files

-   To let someone upload files to that folder, give them access to "read and write" to the folder

    -   Note that if you allow the person you are sharing with to write to the folder, this gives the person you are sharing with the opportunity to delete or replace any files within that folder, so proceed with caution. I recommend creating a specific "sharedwith_X" folder for having someone transfer files to you.

-   Steps

    -   In Globus, click on the folder ("Collection") that you would like to allow file transfer to or from.

    -   Click on "Share", "Add a Shared Endpoint"

    -   To view your shared endpoints, click on "endpoints", "shareable by you"

        -   click on the endpoint and the "sharing" tab

        -   click on "Add Permissions - share with" and enter the email associated with the globus account you want to share with

Question for research computing - can we link Globus with Google drive? https://docs.globus.org/how-to/access-google-storage/
