# Field Safety Protocol

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/field_fieldsafety_protocol.qmd)

------------------------------------------------------------------------

-   [Planning](https://drk-lo.github.io/lotterhoslabprotocols/field_fieldsafety_protocol.html#planning)

-   [Training](https://drk-lo.github.io/lotterhoslabprotocols/field_fieldsafety_protocol.html#training)

-   [Incident Response & Reporting](https://drk-lo.github.io/lotterhoslabprotocols/field_fieldsafety_protocol.html#emergency-procedures)

## **Planning** {.unnumbered}

-   Will you be travelling to another state?

-   Do you anticipate having phone signal

-   What are the local emergency numbers

-   Is anyone on the team first aid/ CPR certified?

### **Identify appropriate equipment, gear and first aid supplies** {.unnumbered}

-   First Aid Kits

-   Jumper cables in vehicles

-   Charged cell phone; satellite phone if you anticipate patchy or no service; extra battery or charger

-   Map, compass, GPS

-   extra food/snacks

-   Hats, sunscreen, sunglasses

-   Appropriate footwear and clothing, layers

-   Flashlight or headlamp

-   Signal/mirror, whistle

-   Knife or multi-tool

## **Training** {.unnumbered}

-   Title IX training

-   First Aid

-   CPR

-   [NU Self Defense Class](https://nupd.northeastern.edu/our-services/safety-training/)

-   https://greaterbostonsafetytraining.org/

### **Emergency procedures** {.unnumbered}

In case of an emergency while in the field:

1.  Assess the situation (do not put yourself in danger)

2.  Contact the emergency officials if needed to be prepared

3.  Address the medical emergency to the extent possible (e.g., first aid, control bleeding,CPR)

    -   [ABC](https://en.wikipedia.org/wiki/ABC_(medicine)) (Airway, Breathing, Circulation)

    -   if you suspect a spinal injury do not move the victim unless they are in imminent danger.

    -   If bleeding, apply pressure to control bleeding

4.  Transport victim to nearest emergency facility

#### **Emergency contact numbers** {.unnumbered}

\|\| Phone number\| \|---\|---\| \|\|**911**\| \|Katie Lotterhos (PI)\|\| \|Remy Gatins \|(805) 704 8877\| \|Madeline Eppley\|\| \|[Northeastern Travel Support Network](https://provost.northeastern.edu/international-travel/health-safety/emergency-assistance/) (for International Emergencies)\|+1.857. 214.5332\| \|Title IX Northeastern University\|\| \|Title IX \|\|

## **Other Resources** {.unnumbered}

-   [UC Field Research Safety](https://www.ucop.edu/safety-and-loss-prevention/_files/field-research-safety/uc-field-research-safety-manual.pdf)
