# Oyster Phenotypic Data Gathering 

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/field_oystersampling.qmd)

------------------------------------------------------------------------

## **Materials ** {.unnumbered}

-   Trays 

-   Shucking knife 

-   Weighing scale 

-   Foil tin boats (1/ oyster)

-   Mini Whirl-Paks (1/ oyster)

-   Brown paper bags (1/ population) 

## Step 1: Pre-Dry 

1. Defrost oysters on the counter 
    - new: deforst overnight in 4C animal fridge

* these instructions are for each oyster, work through each bag one at a time. Make sure to randomize which bags are processed on which day and avoid processing all bags from the same population (ex. FL-4, FL-5, and FL-6) all on one day to avoid batch effects * 

2. Label tins for each oyster to be processed 
2a. Open the Phenotyping Bags page in the app, click "add related phenotyping" - this will auto-generate a unique ID for the oyster. Label 1-2 tin weigh boats (if you can fit both          the tissue and the shell in one boat that is fine, but if the oyster is larger you will likely need two boats). Use a thick sharpie. Label the tag of the tin boat with the individual ID number so that if the dried tissue covers the label, it can still be easily identified. 

3. Place the oyster in the tin.

4. Use calipers to measure the length and width of the oyster. 

5. Shuck oyster open, place the shell in one tins, scrape out tissue onto a paper towel to soak up any excess liquid.

6. Place an empty tin boat on the scale and zero it; then scrape oyster tissue onto the boat and record wet tissue weight (2 decimal points). Once recorded, scrape the tissue into the tin with the shell if space, or into a new labeled tin if more space is needed 

    -   keep all tins in orderly rows on trays
    -   shell and tissue can share a tin as long as they don't touch 

7. Once wet tissue weight is recorded, place trays into a drying oven at 55 C for ~ 20 hours (time point 1), and up to 60 hours (time point 3) 

    -   The temperature and length depend on the size of the oyster - these settings worked for oysters with wet tissue weight within the range of 0.05 - 3.00 g 
    -   New: place in drying oven at 60 C on Friday at 5pm. On Monday morning, remove from dryer once fully dried  (~65 hours drying period) 

## Step 2: After Dry 

1. Remove trays from drying oven; tissue should be dehydrated and stiff but not burnt to a crisp
1a. For each new population, the fastest method is to have one person pre-label the 5 corresponding bags with the oyster ID and vial label, while the other person dislodges each            dried tissue from the tin and prepares them for weighing. Do this for each new population. 

2. Place an empty tin on the scale, zero it, then scrape the oyster tissue in the tin and record the weight. Tissue can now be disposed of. 
2a. To dislodge the tissue, you can first manipulate/ twist the tin boat to encourage the dried tissue to "pop" off, and then go in with a shucking knife to scrape the more stuck-on        parts loose. Make sure to only scrape the tissue and not any dried fluid that may be present. 

3. Place the tin back on the scale, zero if needed, place shell into the tin and record weight. Place shell into corresponding pre-labeled paper bag for storage. 
3a. Note any fouling agents on the shell, for instance if there are any juvenile oysters that cannot be easily shucked off. 

4. Organize shell bags and store in bunker. 
