# Expectations

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/general_expectations.qmd)

------------------------------------------------------------------------

## **These are expectations for everyone in the lab** {.unnumbered}

-   have fun!

-   respect yourself and commit to self care

-   respect each other

-   remember that cutting-edge science is not usually a linear process

-   practice inclusive communication

-   commit to documenting research progress and meeting notes in notebooks on a regular basis

-   commit to file management organization and communicate about the system with the team

-   commit to eliminating distractions during work hours 9am-5pm on weekdays. Distractions include personal texts, push notifications, and personal social media. Ways to eliminate them include turning off notifications and leaving your phone in another location.

-   commit to keeping a task management system, and communicating your priorities and milestones to your advisor(s)

-   commit to keeping a calendar for meetings and plans

-   recognize that shared space is shared resources, keep the lab bench clean, log out of shared computers so others can use them

-   finish what we start (within reason)

-   We all support each other when sh\*t happens.
