# Opentrons OT-2 Pipetting Robot

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/general_OT2-Pipetting-Robot.qmd)

Set up and use instructions.

------------------------------------------------------------------------

## Important Links

[OT-2 Laptop App Download](https://opentrons.com/ot-app/)

[Opentrons OT-2 support and set-up](https://support.opentrons.com/s/ot2-get-started)

[General troubleshooting](https://support.opentrons.com/s/ot2-troubleshooting)

[Public OT-2 protocols library](https://protocols.opentrons.com/)

[Non-coding protocol designer](https://designer.opentrons.com/)

You will need to create a free account to access this protocol designer.

## Protocols

### Starting up and connecting your laptop to the robot

1.  Opentrons pipetting OT-2 robot is located in the MSC shared equipment lab.

2.  Make sure the power cable and USB cable are plugged into the robot and wall.

3.  Download the [Opentrons app](https://opentrons.com/ot-app/). Do not open it yet.

4.  Turn on the robot with the power switch on its back left side. Make sure the blue light on the front of the machine is solid and not flashing and that you hear machinery start-up noises. Start-up can take a minute or two.

5.  [Connect](https://support.opentrons.com/s/article/Get-started-Connect-to-your-OT-2-over-USB) your computer to the USB cable attached to the OT-2. Then, open the Opentrons app after the robot is fully on (troubleshooting [here](https://support.opentrons.com/s/article/Troubleshooting-connection-problems).

6.  In the app, go to the **“Devices”** tab in the left panel. Select the OT-2 robot. 

**Note**:It may take a few minutes for your computer to acknowledge the robot. If after several minutes the robot does not appear, close out of the app, turn the machine off and on, and try the connection steps again.

7.  Install any robot or app updates if prompted (robot updates take several minutes).

**Robot Update Notes**: 

-   You may need to restart the robot and exit and re-enter the app to begin step two of the robot updates. It seems to be a finnicky process.

-   The blue light on the top left of the robot will begin flashing once it has begun downloading the update.

-   The robot may restart itself as part of the update process.

-   The flashing should stop when the update is complete.

### Mounting and Switching Pipet Arms
1.  Remove everything from the robot deck (tip racks, wells, etc.).

2.  Under Devices, select the robot.

3.  Under Pipettes and Modules, click on the three dots for either the left or right pipette mount.

4.  If there is already a pipette in the mount, select detach pipette.

5.  When ready, select “Attach pipette” from the submenu.

6.  Click on “Move pipette to front” and wait for the arm to stop moving forward.

7.  On the next page that pops us, select the pipette model (all our tips are Gen1) and the volume.

8.  Bring the pipette onto the mount. 






