#Clearing Lab Waste

Hello world
 
[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/general_waste_clearing.qmd)

------------------------------------------------------------------------

## Solid waste {.unnumbered}

Most solid waste in our lab consists of pipette tips, small tubes (microcentrifuge tubes, cryovials, tube strips) and, less frequently, a larger tube or a plate used with samples/chemical solutions.\
These used materials are discarded inside waste containers called 'mayo jars'.\
If you are going to generate any solid waste, **label a mayo jar BEFORE you start** using the standard [Hazardous Waste Label](https://github.com/DrK-Lo/lotterhoslabprotocols/blob/15352ee6c5eb6cd71ce45bfaa12fa7bbf951b44f/notebook/Haz_Waste_labels.pdf).\
**NEVER dispose of solid waste inside a unlabelled mayo jar.**

**Sharps**: we also use disposable razor blades frequently when dicing up animal tissue for extractions; all used razor blades MUST be disposed of inside the RED sharps containters in our lab; close the containers' lid when done for the day. Sharps containers are typically not labelled with the Haz Waste Label. **NEVER leave razor blades on the benches**

## Liquid waste {.unnumbered}

Our liquid waste typically consists of extraction/library prep isolation and wash solutions, preservative solutions, such as ethanol and formalin, and plastic-glassware cleaning solutions, such as HCl.\
Liquid waste should **NEVER be mixed indiscriminately** - this can cause serios issues such as thermal reactions/explosions and production of harmful fumes.\
Therefore, keep one waste bottle for each type of waste solution you are generating.\
If you know your work will be generating liquid waste, label each waste bottle **BEFORE you start**, using the standard [Hazardous Waste Label](https://github.com/DrK-Lo/lotterhoslabprotocols/blob/15352ee6c5eb6cd71ce45bfaa12fa7bbf951b44f/notebook/Haz_Waste_labels.pdf)

1.  Managing open stream waste containers:

    -   label the waste containers: fill out all fields EXCEPT the "date container filled" - to keep an open stream bottle (meaning you still expect to produce more of that same waste in the upcoming days/weeks), leave the 'date container filled' field empty;

    -   keep all waste containers in their secondary containment (gray trays) and in the satelitte accumulation areas in our lab as much as possible

    -   make sure that tops are closed tightly once you are done using the waste bottle.

2.  Haz waste disposal: once a waste bottle is at maximum waste volume (3/4 of the total volume) or you are done generating that particular waste

    -   date the bottle ("date container filled")

    -   immediately schedule pickup:

        -   on BioRAFT: Lotterhos Lab \> Waste \> Submit New Waste Pickup Request

        -   email Ryan with number and location of items to be picked up.

Note: Once the label has been dated, pickup request **must** be submitted within 3 days; to be sure it gets done, we recommend that pickup is scheduled immediately (or at leaste before the end of the day). Because we are not on the main campus, Ryan Hill (MSC facilities) does all of our waste pickup so **you must email him to ask him to come to the lab for that specific purpose**; don't hesitate to follow up if he hasn't responded or you see that waste has not been collected within a day or 2. For liquid waste, let him know specifically which containers to pickup (for example, put all containers to be picke up in a separate tray inside the Satelite Accumulation Area and leave a note on the tray saying - "please pickup all 3 bottles inside this tray"). For mayo jars or sharps container, I usually place them on the bench right across from the lab door, inside a cardboard box if possible, with a note as well.
