# FedEx Account

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/general_fedex_ship.qmd)

------------------------------------------------------------------------

## **Lotterhos Lab FedEx account info** {.unnumbered}

-   Account number: ---------432

-   User Id: Lotterhos

-   Pw: see private file

-   Place of birth: see private file

-   My account: 432

Set up the account to receive notifications such as invoice ready to pay, package picked up, package delivered, etc.

## **Create shipping labels** {.unnumbered}

Go to the [account page](https://www.fedex.com/shipping/shipEntryAction.do?method=doEntry&link=1&locale=en_US&urlparams=us&sType=FShipping) & login.

-   Shipping \> Create Shipment

-   Fill out the shipping info and hit Ship - this will create a label (print or send it to the shipper).

-   Drop off labelled package by front office.

The account will be billed later, once the package is picked up.

## **Paying invoices** {.unnumbered}

Go to the [account page](https://www.fedex.com/en-us/home.html) & login, click on your name (top right corner of page) then select "View and pay bill" from the dropdown.

Any due invoices will be under 'All-Open', select the open invoice(s) and hit 'Pay'.

Select the payment method (Lotterhos credit card) and complete payment (*payment info should be already saved in the account*).

Print the receipt to a pdf and place it 'Order and Receipts' (Lotterhos Shared Lab Resources) using the following format for file name: YYYMMDD_FedEx_whatshipped.pdf (example: for ethanol vials shipped to Maine to collect BSB fin clips, 20210712_FedEx_BSBvials.pdf)\
