# Take3 DNA Quantification

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/molecprot_take3dnaquantification.qmd)

The protocol for quantifying DNA/RNA samples using the Take3.

------------------------------------------------------------------------

## **What is the Take3?** {.unnumbered}

The Take3 is like a nanodrop for DNA quantification using spectrophotometry on the plate reader. For more accurate quantification similar to Qubit, considering using the PicoGreen assay.

## **Take3 Run** {.unnumbered}

1.  Select File -\> New Task

2.  When prompted by Task Manager, select Read Now in left pane.

3.  Select Nucleic Acid Quantification (or Protein A280 if measuring proteins) under Take3 Application at the bottom of prompt

4.  Information in top three drop down menus should be autopopulated with plate serial number, well type, and sample type.

5.  Change sample type if desired

6.  Chose Scan 240-300 nm with 2nm step if desired

7.  Click Read. Reader reads the blanks and takes an average, then tray opens.

8.  Click Approve if reading blanks was successful (low %CV value).

9.  You can now specify sample wells. Samples must be in rectangular blocks for reader.

10. Click Read again to read samples. Reader reads samples and once finished ejects tray.

11. Export Data.

12. Blot liquid off with Kimwipe. Store with proper packaging.

13. Replace carrier tray with priming plate.\
