# Seascape Sample Extractions App Use

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/molecprot_SSEapp.qmd)

The Seascape Sample Extractions (SSE) app is an app designed by Katie Lotterhos through Appsheet. It helps keep track of all data relating to the oyster DNA extracted as part of the Model Validation Program experiment. The app connects to this [Google sheet](https://docs.google.com/spreadsheets/d/1nLMK4ucERX90T4lV7ivLZ0HEBaGvwawnA3XHPsKt9Uk/edit) and all data entered in the app shows up in the sheet. As of 07/07/2023, data added to the app will show up in the sheet, but data entered into the sheet will not necessarily populate in the app.

## Accessing the SSE App

To access SSE, Katie will need to send an invite to your Google account. Once you have accepted the invite, you can access the app in the following ways:

- By downloading the Appsheet app to your personal device (phone, tablet, etc)
- Through the [web version](https://www.appsheet.com/start/f58f8dbb-1d41-4d2d-a917-dfe554b1144f#appName=SeascapeSamplesExtractions-6377443&group=%5B%7B%22Column%22%3A%22Date_SentSequencing%22%2C%22Order%22%3A%22Ascending%22%7D%5D&page=deck&sort=%5B%5D&table=1_Plate&view=plate) on a computer

You will need to be signed into an invited Google account to use SSE. We have a lab iPad with the app downloaded and signed into that you are welcome to use.

## App Overview

Use SSE during DNA extractions to enter the following data:

- Extraction dates
- Lysis start and end times
- Weights of tissues before lysis
- Elution buffer info
- DNA quantification data
- Gel images of extracted DNA
- Additional extraction plans for replacement samples

The image below shows your app gallery, or all the Appsheet programs you have access to. Select the Seascape Sample Extractions App.

The app usually opens on the "plate" page. You can switch pages by clicking the icons at the bottom. See also the menu icon and the app refresh button, which you will need to click if any updates are made to the app structure. 

## Data Entry

### Extraction Dates

- At the start of an extraction, you will need to enter it as a new extraction date. Click on the plate you're extracting DNA from on the "plates" page shown above. 

- On the next page that comes up, you'll see a section called "Extraction_plans", which contains the plan label for every sample being extracted in that plate. Scroll down to the "Extraction_Dates" section. Click "Add" to input a new date.

- Fill in the boxes with the requested info. You won't be able to fill in any information past "Time lysis start" on the first day. 

:::{.callout-note}
Remember to come back to this page and fill in the rest of the info as the extraction moves forward.
:::

- Click save when finished. You should be taken back to the overview page of whatever plate you're working with.

### Entering Tissue Weights

- Click on the extraction date that you want to enter tissue weights for. Scroll down to "Extraction_mg_tissues" and click "Add."

- Fill in the data as prompted. Extraction plan keys come from pre-filled dropdown lists of plans for only the plate you're working with, so you don't need to worry about scrolling through plans for all plates. You can find both extraction plan keys and wells by searching for them by well in the search bar.

- Click save when finished.

### Entering Quantification Data and Gels

- If you are entering quantification data that was obtained using a PicoGreen assay, you will first need to enter the assay standard data.

- In the extraction date you're entering quant data for, scroll down to "plate_standards" and click "Add."

- Enter the standard line equation slope and intercept. Give the standard entry a descriptive label that includes the plate label and the columns of that plate that the standard represents (ex. CviMVP_PlDNA_3_cols1_6). Click save when finished.

- Go back to the page for the extraction date you want to enter quant data for. Scroll down to "DNA_quantifications" and click "Add" to enter data.

- Enter the info as prompted. If you are entering quant data from PicoGreen, make sure to select the right plate_standards_key. You can leave this entry blank if entering Qubit data.

:::{.callout-note}
## Explanation of the corr_conc_ng_uL_auto box

We have found that PicoGreen assay concentrations are on average 2 times larger than those produced by Qubit. Qubit tends to produce the same data for the same sample much more reliably than PicoGreen, so we apply a correction factor to PicoGreen concentrations to account for this. The corr_conc_ng_uL_auto box automatically divides PicoGreen concentrations from platereader_conc_ng_uL_auto by 2. This corrected concentration is what is used in data analysis going forward. 

No correction factors are applied to Qubit concentrations, so the concentration that appears in the qubit_conc_ng_uL box is the same that will appear in the corrected box.
:::

- The quant_status box automatically populates with "Good," "Concentrate," or "Reextract" based on the corrected sample concentration. 

- To add info about the sample's quality on the gel, click save on the quant page, then go back to the extraction date page. Scroll down to "gel_images" and click "Add."

- Fill in the data as prompted. For the ladder link entry, you can copy and paste previous ladder link entries from the spreadsheet if you're still using 1kb Plus GeneRuler ladders. Click save when finished.

- Go back to the quant section and select the sample you want to include gel data for. Scroll down past the concentration data entry section until you reach the gel section. Select the gel image for that sample and its quality.

- Click save.

## Replacement Samples

- If for some reason a sample in the original extraction plan is unable to be extracted (not enough tissue, unable to locate sample, etc.), you will need to find a replacement sample, and create an extraction plan for it in the app.

### Replacement Sample Selection

- In the [Seascape Sample Extraction Google sheet](https://docs.google.com/spreadsheets/d/1nLMK4ucERX90T4lV7ivLZ0HEBaGvwawnA3XHPsKt9Uk/edit#gid=1504845155), find the sample that needs replacing in the "plan" tab. Take note of the Label_ind, which is usually SG_####.

- Search the plan tab for individual labels that come numerically before and after the sample needing replacing. If you want to replace sample SG_1456, search for samples SG_1454, SG_1455, SG_1457, etc. You don't want to replace a sample with another that has already been or will be extracted. There may be extraction plans outside of those listed in the Seascape Sample Extractions sheet, so be sure to check those as well.

- Once you find a sample that does not turn up in any existing extraction plans, open the [Seascape Samples Google sheet](https://docs.google.com/spreadsheets/d/1jK4Qhd8_yIoEntUfu2XR2Ul9OdKDfrOf7Ehc7ULwS3E/edit#gid=1863221382) (different from the extraction sheet). In the "tissue" tab, use Ctrl + F to search for the label_ind of the new sample. Check to make sure its location origin is the same as that of the original sample by looking at ID_SiteDate.

-  Each individual should have 3 entries in the tissue tab: mantle, gonad, and gill. Look for the vial number that has the gill of the selected individual.

- Now you're ready to enter the new replacement sample in the app

### Entering Replacements in the App

- On the plate page, click the + symbol to add a new plate. Name it as the name of the plate the replacement sample is for and "replace." 

  - Ex. CviMVP_PlDNA_4_Replace

- Click on the replacement plate and under "extraction_plans," click Add.

- Follow the prompts to enter the data needed to make a new extraction plan for the replacement sample. The majority of this info can be found in the "tissue" tab in the Seascape Samples datasheet. You will need to look at the "date" tab to find the SiteDate_key. Click save when finished.

- You can add as many replacements as you need for any given plate. We (Nicole and Kiran) and have found that if you are extracting several replacements at the same time, it's easiest to create one extraction date for all of them and proceed as you normally would with data entry for a plate extraction.

:::{.callout-important}
## Don't Delete Original Samples
You **do not** need to delete original samples from the extraction plan sheet or from past data if you replace it with a new one. It's important to keep a record of when we replaced samples and what we replaced them with, and keeping everything in the data like this lets us have that track record.
:::

## Re-extractions

- If certain samples do not have a high enough DNA concentration or have poor gel quality, you will need to re-extract them using the Qiagen individual extraction kit.

- When doing re-extractions, go into the plate that the samples are part of. Make a new extraction date for each single re-extraction you're doing. For example, if you need to re-extract samples B4 and G6 from plate 4 on August 5, 2023, you would make 2 new extraction dates labeled:
  - CviMVP_PlDNA_4_20230805_B4
  - CviMVP_PlDNA_4_20230805_G6

:::{.callout-note}
## Replacements vs. Re-extractions
Unlike with replacement samples, you do not need to make a whole new plate for re-extractions, nor do you need to create new extraction plans for re-extractions.
:::

- Once you create the new extraction dates, you can continue entering data into the app as you normally would for any other extraction. In this case, each re-extraction replacement date will only include one sample. 

## Transferring DNA Volumes to the Final Shipment Plate

- Once all extractions and re-extractions have been completed for a plate and all the samples are marked as "Final," you can use the quant table in the app and spreadsheet to help when transferring DNA to your final plate. 

- For each well, the spreadsheet will automatically calculate the volume of DNA needed to get 400ng of DNA into your final plate. This calculation is done based on the corr_conc_ng_ul_auto column (DNA concentration).  Transfer this volume into your final plate well. 

- The spreadsheet will also calculate the volume of molecular grade water needed for each well in the final plate to reach a total volume of 30ul. Add this volume to your final plate as well. 

## Exporting Final Data to a CSV for Shipment

- 
