# Changing Gonad Buffer

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/molecprot_gonad_buffer.qmd)

Protocol for changing the ethanol out of gonad tissue vials.

------------------------------------------------------------------------

We are switching to a 95Etoh-PureNoAdditives buffer.
See [types of ethanol page](https://github.com/DrK-Lo/lotterhoslabprotocols/blob/3689d797871137dc6ae6eedd4959b8365b184d0c/molecprot_etoh) to understand why we are changing the ethanol out of gonad vials.

## Steps for changing ethanol out of gonad tissue vials

1. Centrigue the vial for 2 minutes at full speed
2. Use a pipette, suck up the 95MGetoh ethanol buffer

**Note**: Make sure to not suck up any tissue!

3. Add the 95Etoh-PureNoAdditives ethanol buffer


## Exceptions

### For cryovials that do not fit in the certifuge

Transfer the tissue into a o-ring with a label for long term storage

### For vials with too much gonad and not enough ethanol (over 1:5 tissue-to-ethanol)

You may remove some of the tissue from the vial, but make sure there is at least 1:5 tissue-to-ethanol.
