# Gel Electrophoresis

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/molecprot_gelelectrophoresis.qmd)

The protocol for running a gel. Madeline's lab notebook (labeled "Eppley") has written protocols and troubleshooting for gels on pages 2-3. 

------------------------------------------------------------------------

We are Ethidium-Bromide Free!

## **Materials and Equipment** {.unnumbered}

1.  Agarose

2.  1X TAE (you can also use TBE, but we regularly have TAE stock pre-made). Here's a link to a [TAE recipe](http://cshprotocols.cshlp.org/content/2006/1/pdb.rec8644.full) for TAE. We should have all materials in the lab. If using 10x TAE stock, dilute with 100 mL TAE to 900 mL milliq water.

3.  GelRed® 10,000X stock reagent (left-top drawer in the room with gel docks).

4.  Erlenmeyer flask (should be in the room with gel docks).

## Protocol {.unnumbered}

5.  Tare a weigh boat on the scale.

6.  Add 1.4 g of agarose to the weigh boat.

7.  Pour 70 mL of 1x TAE buffer into a graduated cylinder.

8.  Pour 35-40 mL of the TAE buffer into an Erlenmeyer flask, then add the agarose and swirl.

9.  Microwave solution for \~45 seconds, or until it begins to boil.

10. Add more TAE buffer, but leave 10-20 mL in the graduated cylinder.

11. Microwave solution again until it begins to boil. Repeat until agarose is completely dissolved.

12. Add remaining TAE buffer (to cool solution).

13. Dilute the GelRed® 10,000X stock reagent into the molten agarose gel solution at 1:10,000 and mix thoroughly.

    -   (e.g., 5 µL of the GelRed 10,000X stock reagent added to 50 mL of the gel solution)

## **Running the Gel** {.unnumbered}

-   This source detailes a full protocol for running a gel: https://www.addgene.org/protocols/gel-electrophoresis/

-   Source from Remy for Gel protocol (note that this is for an Ethidium Bromide system, and we are Ethidium-Bromide free at the MSC): [Gel Electrophoresis protocol_lab interns.pdf](https://github.com/DrK-Lo/lotterhoslabprotocols/files/8584679/Gel.Electrophoresis.protocol_lab.interns.pdf)\
