<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lotterhos Lab Protocols – molecprot_magbeadwash</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./molecprot_tapestationlibrarycheck.html" rel="next">
<link href="./molecprot_picoGreenAssay.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Lotterhos Lab Protocols</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/Lotterhos_logo2.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">General</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_welcome.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_expectations.html" class="sidebar-item-text sidebar-link">Expectations</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_GettingStarted.html" class="sidebar-item-text sidebar-link">Getting Started in the Lab</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_waste_clearing.html" class="sidebar-item-text sidebar-link">Clearing Lab Waste</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_ShippingHazMat.html" class="sidebar-item-text sidebar-link">Shipping of Hazardous Materials</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_shared_equipment.html" class="sidebar-item-text sidebar-link">NUMSC - Shared Lab Space</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_reimbursement.html" class="sidebar-item-text sidebar-link">Reimbursement</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_receiving.html" class="sidebar-item-text sidebar-link">Receiving Supplies and Equipment</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_purchasing.html" class="sidebar-item-text sidebar-link">Purchasing</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_ordering.html" class="sidebar-item-text sidebar-link">Ordering Supplies and Equipment</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_MVI-scope-camera.html" class="sidebar-item-text sidebar-link">Scope Camera MVI Nikon SMZ 1000</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_freezer.html" class="sidebar-item-text sidebar-link">Freezer Alarm System</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_fedex_ship.html" class="sidebar-item-text sidebar-link">FedEx Account</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_creating_barcoded_labels.html" class="sidebar-item-text sidebar-link">Creating Barcoded Labels</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_chemical_inventory.html" class="sidebar-item-text sidebar-link">Managing Chemical Inventory</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./general_autoclave.html" class="sidebar-item-text sidebar-link">Autoclave (OGL)</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">Professional Development</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./profdev.html" class="sidebar-item-text sidebar-link">Professional Development Resources</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./profdev_ReducingCognitiveLoad.html" class="sidebar-item-text sidebar-link">Reducing Cognitive Load</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./profdev_How-to-publish-a-paper.html" class="sidebar-item-text sidebar-link">How to Publish a Paper</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./profdev_design.html" class="sidebar-item-text sidebar-link">Design</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./profdev_courses.html" class="sidebar-item-text sidebar-link">Graduate Courses</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">Molecular Protocols</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_barcodesnindexes.html" class="sidebar-item-text sidebar-link">Determining Barcodes and Indexes for Illumina Sequencing</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_dnaextractionomega.html" class="sidebar-item-text sidebar-link">DNA Extraction (Omega)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_dnaextractionqiagen.html" class="sidebar-item-text sidebar-link">DNA Extraction (Qiagen)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_dnaextractionspartina.html" class="sidebar-item-text sidebar-link">DNA Extraction (Spartina)</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_gelelectrophoresis.html" class="sidebar-item-text sidebar-link">Gel Electrophoresis</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_illuminalibraryprep.html" class="sidebar-item-text sidebar-link">Illumina Library Prep</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_qPCR-Libraryquant.html" class="sidebar-item-text sidebar-link">Library Quantification</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_rnaextraction.html" class="sidebar-item-text sidebar-link">RNA Extraction</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_solutionrecipes.html" class="sidebar-item-text sidebar-link">Solution Recipes</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_etoh.html" class="sidebar-item-text sidebar-link">Types of Ethanol</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_gonad_buffer.html" class="sidebar-item-text sidebar-link">Changing Gonad Buffer</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Molecular Equipment</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_take3dnaquantification.html" class="sidebar-item-text sidebar-link">Take3 DNA Quantification</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_picoGreenAssay.html" class="sidebar-item-text sidebar-link">PicoGreen Assay</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_magbeadwash.html" class="sidebar-item-text sidebar-link active">Magnetic Bead Wash</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_tapestationlibrarycheck.html" class="sidebar-item-text sidebar-link">TapeStation Library Check</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_qPCRandBioRAD.html" class="sidebar-item-text sidebar-link">Molecular Protocols for Using the BioRAD qPCR Machine</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./molecprot_outdated.html" class="sidebar-item-text sidebar-link">Outdated Molecular Protocols</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">Field and Sampling Protocols</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_collectsampdna.html" class="sidebar-item-text sidebar-link">Collecting Samples for DNA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_collectsamprna.html" class="sidebar-item-text sidebar-link">Collecting Samples for RNA</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_conductivityloggers.html" class="sidebar-item-text sidebar-link">Conductivity Loggers</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_fieldsafety_protocol.html" class="sidebar-item-text sidebar-link">Field Safety Protocol</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_oystersampling.html" class="sidebar-item-text sidebar-link">Oyster Sampling</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_kayak.html" class="sidebar-item-text sidebar-link">Lab Kayak Care</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_phloggers.html" class="sidebar-item-text sidebar-link">pH Loggers</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_Seatables.html" class="sidebar-item-text sidebar-link">Managing Seatables</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./field_watersampling.html" class="sidebar-item-text sidebar-link">Water Sampling</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">Coding Protocols</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_bioinformatics.html" class="sidebar-item-text sidebar-link">Bioinformatics Resources</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_checksums.html" class="sidebar-item-text sidebar-link">Transferring Files md5</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_defiance.html" class="sidebar-item-text sidebar-link">Accessing and Using Defiance Cluster</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_directoryorganization.html" class="sidebar-item-text sidebar-link">General Directory Organization</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_githhubMarkdown.html" class="sidebar-item-text sidebar-link">GitHub Figures</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_LearningToCode.html" class="sidebar-item-text sidebar-link">Learning to Code</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_pathAndAliasMod.html" class="sidebar-item-text sidebar-link">Setting Alias or PATH variable</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_pseudoparallel.html" class="sidebar-item-text sidebar-link">Pseudo-Parallelize Your Code on the Cluster</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_setseeds.html" class="sidebar-item-text sidebar-link">Setting Seeds for Reproducibility</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_TroubleshootingCellprofiler.html" class="sidebar-item-text sidebar-link">Troubleshooting CellProfiler Installation</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_unixcommands.html" class="sidebar-item-text sidebar-link">Basic Unix Commands</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_versioncontrol.html" class="sidebar-item-text sidebar-link">Version Control with GitHub</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_quarto.html" class="sidebar-item-text sidebar-link">Editing with Quarto</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">Discovery</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_slurmArrays.html" class="sidebar-item-text sidebar-link">Parallelization with Array</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_nonNEUpersonnel.html" class="sidebar-item-text sidebar-link">Instructions for Discovery for Non-Northeastern Personnel</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_integrated-development-environment.html" class="sidebar-item-text sidebar-link">What are VS Code and PyCharm?</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_6-optimization.html" class="sidebar-item-text sidebar-link">Optimizing</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_5-parallelization.html" class="sidebar-item-text sidebar-link">Workflow Parallelization Approaches</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_4-examples.html" class="sidebar-item-text sidebar-link">Example Scripts</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_3-storage.html" class="sidebar-item-text sidebar-link">Lotterhos Lab vs.&nbsp;Personal Storage on Discovery</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_2-globus.html" class="sidebar-item-text sidebar-link">Globus File Transfer</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_1a-OOD.html" class="sidebar-item-text sidebar-link">Open OnDemand</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discovery_1-gettingstarted.html" class="sidebar-item-text sidebar-link">Connecting to the Discovery Cluster</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#magnetic-bead-wash" id="toc-magnetic-bead-wash" class="nav-link active" data-scroll-target="#magnetic-bead-wash">Magnetic Bead Wash</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><strong>Overview</strong></a></li>
  <li><a href="#table-of-contents" id="toc-table-of-contents" class="nav-link" data-scroll-target="#table-of-contents"><strong>Table of Contents</strong></a>
  <ul class="collapse">
  <li><a href="#protocols" id="toc-protocols" class="nav-link" data-scroll-target="#protocols"><strong>Protocols</strong></a></li>
  <li><a href="#troubleshooting" id="toc-troubleshooting" class="nav-link" data-scroll-target="#troubleshooting"><strong>Troubleshooting</strong></a></li>
  </ul></li>
  <li><a href="#protocols-1" id="toc-protocols-1" class="nav-link" data-scroll-target="#protocols-1"><strong>Protocols</strong></a>
  <ul class="collapse">
  <li><a href="#cleanup-genomic-dna" id="toc-cleanup-genomic-dna" class="nav-link" data-scroll-target="#cleanup-genomic-dna"><strong>Cleanup genomic DNA</strong></a></li>
  <li><a href="#notes" id="toc-notes" class="nav-link" data-scroll-target="#notes"><strong>Notes</strong></a></li>
  </ul></li>
  <li><a href="#cleanup-of-fragmented-dna" id="toc-cleanup-of-fragmented-dna" class="nav-link" data-scroll-target="#cleanup-of-fragmented-dna"><strong>Cleanup of fragmented DNA</strong></a>
  <ul class="collapse">
  <li><a href="#notes-1" id="toc-notes-1" class="nav-link" data-scroll-target="#notes-1"><strong>Notes</strong></a></li>
  </ul></li>
  <li><a href="#size-selection" id="toc-size-selection" class="nav-link" data-scroll-target="#size-selection"><strong>Size Selection</strong></a>
  <ul class="collapse">
  <li><a href="#notes-2" id="toc-notes-2" class="nav-link" data-scroll-target="#notes-2"><strong>Notes</strong></a></li>
  </ul></li>
  <li><a href="#factors-that-impact-overall-performance" id="toc-factors-that-impact-overall-performance" class="nav-link" data-scroll-target="#factors-that-impact-overall-performance"><strong>Factors that Impact Overall Performance</strong></a>
  <ul class="collapse">
  <li><a href="#upper-size-limit-modification" id="toc-upper-size-limit-modification" class="nav-link" data-scroll-target="#upper-size-limit-modification"><strong>Upper size limit | Modification</strong></a></li>
  <li><a href="#lower-size-limit-modification" id="toc-lower-size-limit-modification" class="nav-link" data-scroll-target="#lower-size-limit-modification"><strong>Lower size limit | Modification</strong></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="magnetic-bead-wash" class="level1">
<h1>Magnetic Bead Wash</h1>
<p><a href="https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/molecprot_magbeadwash.qmd">Edit this page</a></p>
<p>The protocol for doing a magnetic bead wash.</p>
<hr>
<section id="overview" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="overview"><strong>Overview</strong></h2>
<p>Magnetic beads are used for purification and size selection of single or double-stranded DNA. size selection may be performed at the following points during the overall library construction process:</p>
<ul>
<li><p>before or after DNA fragmentation;</p></li>
<li><p>after individual enzymatic reactions;</p></li>
<li><p>after the first post-ligation cleanup; or</p></li>
<li><p>after library amplification.</p></li>
</ul>
<p>We use <a href="https://www.kapabiosystems.com/document/kapa-pure-beads-tds/?dl=1">Kapa Pure Beads</a> for magnetic bead washes. We find that they work as well as the Ampure Beads and are MUCH cheaper.</p>
<p>Before using, be sure to read the <a href="https://www.kapabiosystems.com/document/kapa-pure-beads-tds/?dl=1">PDF</a> from Kapa.</p>
</section>
<section id="table-of-contents" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="table-of-contents"><strong>Table of Contents</strong></h2>
<section id="protocols" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="protocols"><strong>Protocols</strong></h3>
<p><a href="https://drk-lo.github.io/lotterhoslabprotocols/molecprot_magbeadwash.html#cleanup-genomic-dna">Clean up genomic DNA</a></p>
<p><a href="https://drk-lo.github.io/lotterhoslabprotocols/molecprot_magbeadwash.html#cleanup-of-fragmented-dna">Cleanup of fragmented DNA</a></p>
<p><a href="https://drk-lo.github.io/lotterhoslabprotocols/molecprot_magbeadwash.html#size-selection">Size Selection</a></p>
</section>
<section id="troubleshooting" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="troubleshooting"><strong>Troubleshooting</strong></h3>
<p><a href="https://drk-lo.github.io/lotterhoslabprotocols/molecprot_magbeadwash.html#factors-that-impact-overall-performance">Factors that Impact Overall Performance</a></p>
</section>
</section>
<section id="protocols-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="protocols-1"><strong>Protocols</strong></h2>
<p>See the <a href="https://www.kapabiosystems.com/document/kapa-pure-beads-tds/?dl=1">PDF</a> for the complete protocol. Tips:</p>
<section id="cleanup-genomic-dna" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="cleanup-genomic-dna"><strong>Cleanup genomic DNA</strong></h3>
<p>1.1 Ensure that KAPA Pure Beads has been equilibrated to room temperature and that the beads are fully resuspended before proceeding.</p>
<p>1.2 Add 300 μL of KAPA Pure Beads (3:1 ratio for gDNA) to the 100 μL genomic DNA sample.</p>
<p>1.3 Mix thoroughly by vortexing and/or pipetting up and down multiple times.</p>
<p>1.4 Incubate the plate/tube(s) at room temperature for 10 min to bind the DNA to the beads.</p>
<p>1.5 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear.</p>
<p>1.6 Carefully remove and discard the supernatant.</p>
<p>1.7 Keeping the plate/tube(s) on the magnet, add 200 μL of 80% ethanol.</p>
<p>1.8 Incubate the plate/tube(s) on the magnet at room temperature for ≥30 sec.</p>
<p>1.9 Carefully remove and discard the ethanol.</p>
<p>1.10 Keeping the plate/tube(s) on the magnet, add 200 μL of 80% ethanol.</p>
<p>1.11 Incubate the plate/tube(s) on the magnet at room temperature for ≥30 sec.</p>
<p>1.12 Carefully remove and discard the ethanol. Try to remove all residual ethanol without disturbing the beads.</p>
<p>1.13 Dry the beads at room temperature for 3 – 5 min, or until all of the ethanol has evaporated. Caution: over-drying the beads may result in reduced yield.</p>
<p>1.14 Remove the plate/tube(s) from the magnet.</p>
<p>1.15 Resuspend the beads in an appropriate volume of pre-heated elution buffer at 37°C and/or perform the elution incubation (step 1.16) in a thermocycler or heating block set to 37°C. The appropriate elution buffer may be either 10 mM Tris-HCl, (pH 8.0 – 8.5) or PCR-grade water, depending on the downstream application.</p>
<p>1.16 Incubate the plate/tube(s) for 10 min to elute the DNA off the beads.</p>
<p>1.17 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear.</p>
<p>1.18 Transfer the clear supernatant to a new plate/ tube(s). Proceed with your downstream application, or store DNA at 4ºC for 1 – 2 weeks, or at -20ºC.</p>
</section>
<section id="notes" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="notes"><strong>Notes</strong></h3>
<ul>
<li><p>3X KAPA Pure Beads to-sample volumetric ratio recommended</p></li>
<li><p>The detailed protocol below is an example of a 3X cleanup of genomic DNA in 100 µL. Please pay special attention to steps 1.15 and 1.16 (elution of DNA off beads). To ensure optimal recovery, these steps may be performed at an elevated temperature: 37°C for 10 min. Elution buffer may be pre-heated for this step and/or the elution performed in a thermocycler or heating block.</p></li>
<li><p>As indicated above, a heated elution is recommended to ensure optimal recovery of high-quality genomic DNA. This is not a requirement for the cleanup of other DNA types (e.g.&nbsp;fragmented DNA).</p></li>
<li><p>For maximum recovery of the original DNA sample during cleanup, buffer exchange, and/or concentration of genomic DNA, fragmented DNA for NGS library construction, PCR or qPCR products—regardless of quality—a KAPA Pure Beads-to-sample volumetric ratio of 3X is recommended. Expected recoveries are 50 – 90%, depending upon sample quality and quantity. If a lower ratio is used, it may result in lower yields and exclusion of smaller fragments.</p></li>
</ul>
</section>
</section>
<section id="cleanup-of-fragmented-dna" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="cleanup-of-fragmented-dna"><strong>Cleanup of fragmented DNA</strong></h2>
<p>2.1 Ensure that KAPA Pure Beads has been equilibrated to room temperature and that the beads are fully resuspended before proceeding.</p>
<p>2.2 Add 80 μL of KAPA Pure Beads to the 100 μL fragmented DNA sample.</p>
<p>2.3 Mix thoroughly by vortexing and/or pipetting up and down multiple times.</p>
<p>2.4 Incubate the plate/tube(s) at room temperature for 5 – 15 min to bind the DNA to the beads.</p>
<p>2.5 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear.</p>
<p>2.6 Carefully remove and discard the supernatant.</p>
<p>2.7 Keeping the plate/tube(s) on the magnet, add 200 μL of 80% ethanol.</p>
<p>2.8 Incubate the plate/tube(s) on the magnet at room temperature for ≥30 sec.</p>
<p>2.9 Carefully remove and discard the ethanol.</p>
<p>2.10 Keeping the plate/tube(s) on the magnet, add 200 μL of 80% ethanol.</p>
<p>2.11 Incubate the plate/tube(s) on the magnet at room temperature for ≥30 sec.</p>
<p>2.12 Carefully remove and discard the ethanol. Try to remove all residual ethanol without disturbing the beads.</p>
<p>2.13 Dry the beads at room temperature for 3 – 5 min, or until all of the ethanol has evaporated. Caution: over-drying the beads may result in reduced yield.</p>
<p>2.14 Remove the plate/tube(s) from the magnet.</p>
<p>2.15 Resuspend the beads in an appropriate volume of elution buffer (10 mM Tris-HCl, pH 8.0 – 8.5) or PCR-grade water, depending on the downstream application.</p>
<p>2.16 Incubate the plate/tube(s) at room temperature for 2 min to elute the DNA off the beads. The elution time may be extended up to 10 min if necessary to improve DNA recovery.</p>
<p>2.17 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear.</p>
<p>2.18 Transfer the clear supernatant to a new plate/ tube(s). Proceed with your downstream application, or store DNA at 4ºC for 1 – 2 weeks, or at -20ºC.</p>
<section id="notes-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="notes-1"><strong>Notes</strong></h3>
<ul>
<li>0.8X cleanup of a 100 µL fragmented DNA sample recommended (will retain fragments greater than 300 bp)</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Fragments to be retained</strong></th>
<th style="text-align: center;"><strong>Recommended Beads-to-sample ratio</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">≥ kb</td>
<td style="text-align: center;">0.5X</td>
</tr>
<tr class="even">
<td style="text-align: center;">≥ 450 bp</td>
<td style="text-align: center;">0.6X</td>
</tr>
<tr class="odd">
<td style="text-align: center;">≥ 350 bp</td>
<td style="text-align: center;">0.7X</td>
</tr>
<tr class="even">
<td style="text-align: center;">≥ 300 bp</td>
<td style="text-align: center;">0.8X</td>
</tr>
<tr class="odd">
<td style="text-align: center;">≥ 250 bp</td>
<td style="text-align: center;">0.9X</td>
</tr>
<tr class="even">
<td style="text-align: center;">≥ 150 bp</td>
<td style="text-align: center;">1.5X</td>
</tr>
<tr class="odd">
<td style="text-align: center;">≥ 100 bp</td>
<td style="text-align: center;">2.2X -3X</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="size-selection" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="size-selection"><strong>Size Selection</strong></h2>
<p>3.1 Ensure that KAPA Pure Beads has been equilibrated to room temperature and that the beads are fully resuspended before proceeding.</p>
<p>3.2 Perform the first size cut (0.6X, to exclude large library fragments) by adding 30 μL of KAPA Pure Beads to 50 μL of adapter-ligated library (0.6 x 50 μL = 30 μL).</p>
<p>3.3 Mix thoroughly by vortexing and/or pipetting up and down multiple times.</p>
<p>3.4 Incubate the plate/tube(s) at room temperature for 5 – 15 min to bind large library molecules (&gt;450 bp) to the beads.</p>
<p>3.5 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear.</p>
<p>3.6 Carefully transfer the supernatant containing the smaller library molecules (&lt;450 bp) to a new plate/ tube(s). It is critical that no beads are transferred with the supernatant.</p>
<p>3.7 Discard the plate/tube(s) containing the beads to which library fragments larger than ~450 bp are bound.</p>
<p>3.8 Perform the second size cut (0.8X) by adding 10 μL of KAPA Pure Beads to the supernatant. This volume is calculated relative to the original sample volume of 50 μL, e.g., (0.8 – 0.6) x 50 μL = 10 μL.</p>
<p>3.9 Mix thoroughly by vortexing and/or pipetting up and down multiple times.</p>
<p>3.10 Incubate the plate/tube(s) at room temperature for 5 – 15 min to bind library molecules &gt;250 bp to the beads.</p>
<p>3.11 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear. Carefully remove and discard the supernatant which contains library molecules smaller than</p>
<blockquote class="blockquote">
<p>250 bp.</p>
</blockquote>
<p>3.12 Keeping the plate/tube(s) on the magnet, add 200 μL of 80% ethanol.</p>
<p>3.13 Incubate the plate/tube(s) on the magnet at room temperature for ≥30 sec.</p>
<p>3.14 Carefully remove and discard the ethanol. 3.15 Keeping the plate/tube(s) on the magnet, add 200 μL of 80% ethanol.</p>
<p>3.16 Incubate the plate/tube(s) on the magnet at room temperature for ≥30 sec.</p>
<p>3.17 Carefully remove and discard the ethanol. Try to remove all residual ethanol without disturbing the beads.</p>
<p>3.18 Dry the beads at room temperature for 3 – 5 min, or until all of the ethanol has evaporated. ⚠️ <strong>Caution: over-drying the beads may result in reduced yield.</strong></p>
<p>3.19 Remove the plate/tube(s) from the magnet.</p>
<p>3.20 Thoroughly resuspend the beads in the required volume of elution buffer (10 mM Tris-HCl, pH 8.0 – 8.5), or PCR-grade water, depending on the downstream application.</p>
<p>3.21 Incubate the plate/tube(s) at room temperature for 2 min to elute DNA off the beads. The elution time may be extended up to 10 min if necessary to improve DNA recovery.</p>
<p>3.22 Place the plate/tube(s) on a magnet to capture the beads. Incubate until the liquid is clear.</p>
<p>3.23 Transfer the clear supernatant with size-selected DNA to a new plate/tube(s). Proceed with your downstream application, or store DNA at 4ºC for 1 – 2 weeks, or at -20ºC.</p>
<section id="notes-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="notes-2"><strong>Notes</strong></h3>
<p>Bead-based size selection or “double-sided size selection” consists of a “first” and “second cut”, represented as ratios of beads-to-sample volumes.</p>
</section>
</section>
<section id="factors-that-impact-overall-performance" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="factors-that-impact-overall-performance"><strong>Factors that Impact Overall Performance</strong></h2>
<ul>
<li><p>Store at 2°C to 8°C in a constant-temperature refrigerator; do not store at -20°C. <strong>Always ensure that KAPA</strong> <strong>Pure Beads is fully equilibrated to room temperature</strong> <strong>before use.</strong></p></li>
<li><p>For optimal performance, always ensure that the KAPA Pure Beads is equilibrated to room temperature, that the beads are fully resuspended before use, and that the DNA and bead solutions are thoroughly mixed prior to the binding incubation.</p></li>
<li><p>The volumetric ratio of KAPA Pure Beads to sample is the critical factor in determining the size distribution of DNA fragments retained by the beads. The volume (ratio) may be modified/optimized based upon the specific application and/or point in the library construction workflow where a cleanup or size selection is employed.</p></li>
<li><p>The volume in which cleanups and size selection are performed may impact performance. DNA samples may be diluted in 10 mM Tris-HCl (pH 8.0 – 8.5) or PCR-grade water to increase the working volume prior to the addition of KAPA Pure Beads. This is recommended for starting volumes &lt;50 µL, DNA preparations that are viscous, and/ or contain a high concentration of salts or PEG.</p></li>
<li><p>It is important to prepare fresh 80% ethanol prior to use, since ethanol absorbs atmospheric water.</p></li>
<li><p>The volume of 80% ethanol used for bead washes may be adjusted to accommodate different plate/tube volumes and/or limited pipetting capacity, but it is important that the beads are entirely submerged during the wash steps. Where possible, use a wash volume that is equal to the volume of sample plus KAPA Pure Beads.</p></li>
<li><p>It is important to remove all ethanol before proceeding with subsequent reactions. However, over-drying of beads may make them difficult to resuspend, and may result in a dramatic loss of DNA. Drying of beads for 3 – 5 min at room temperature should be sufficient. Drying of beads at 37ºC is not recommended.</p></li>
<li><p>Elution time and temperature may impact DNA recovery, particularly for high-molecular weight genomic DNA.</p></li>
<li><p>Purified DNA in elution buffer should be stable at 4°C for 1 – 2 weeks, or for at least 1&nbsp;month at -20°C. The long-term stability of library DNA at -20°C depends on a number of factors, including library concentration. Always use low DNA-binding tubes for long-term storage and avoid excessive freezing and thawing.</p></li>
<li><p>To increase the recovery of DNA at a specific stage in an NGS library construction protocol, the volume of KAPA Pure Beads used in the cleanup may be increased, but this will most likely result in the retention of smaller DNA fragments.</p></li>
</ul>
<section id="upper-size-limit-modification" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="upper-size-limit-modification"><strong>Upper size limit | Modification</strong></h3>
<ul>
<li><p>Increase upper size limit: Decrease the ratio of the first cut</p></li>
<li><p>Decrease upper size limit: Increase the ratio of the first cut</p></li>
</ul>
</section>
<section id="lower-size-limit-modification" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="lower-size-limit-modification"><strong>Lower size limit | Modification</strong></h3>
<ul>
<li><p>Increase lower size limit: Decrease the ratio of the second cut</p></li>
<li><p>Decrease lower size limit: Increase the ratio of the second cut</p></li>
<li><p>The second size cut should be performed with at least 0.2&nbsp;volumes of KAPA Pure Beads. Please note the volume of the KAPA Pure Beads needed for the second cut is calculated relative to the volume of the sample at the start of the size selection procedure, not the volume of the DNA-containing supernatant transferred after the first cut. DNA recovery is dramatically reduced if the difference between the first and second cuts is less than ~0.2&nbsp; volumes. To increase the amount of DNA recovered, more than 0.2&nbsp;volumes of KAPA Pure Beads may be used for the second cut, but note that this may result in the recovery of smaller library fragments and a broader size distribution.</p></li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'alternate';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./molecprot_picoGreenAssay.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">PicoGreen Assay</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./molecprot_tapestationlibrarycheck.html" class="pagination-link">
        <span class="nav-page-text">TapeStation Library Check</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>