# Plate DNA Extraction (Qiagen)

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/molecprot_dnaextractionqiagenplate.qmd)

The protocol for extracting DNA from a full plate with the Qiagen Tissue Kit.

------------------------------------------------------------------------

This protocol is for oysters (Crassostrea virginica)

## **Materials and Equipment** {.unnumbered}

### **Qiagen Extraction Kits** {.unnumbered}

**Qiagen Blood and Tissue Extraction Kit - 96 plate**

-   4x96 (384 samples) - Cat No./ID: 69506 - \~1300\$

-   \~3.40\$ per sample

### **Additional Reagents and Consumables** {.unnumbered}

-   Sterile Scalpel blades + blue plastic disposal container

-   Alcohol lamp (requires minimum 90% ethanol)

-   Flame (sterilization)

-   Weigh paper

-   Kim wipes

-   Pipette Tips (300uL)

-   Easy Pet + Serological Tips

-   Liquid boats

-   EtoH (100% - molecular grade)

-   Plastic sheet

### **Equipment** {.unnumbered}

-   Micro-scale (need to be able to measure down to 20mg)

-   Thermo-mixer (with plate attachments - plates from kit are too tall for our Thermo-mixer) - check temperature ranges

-   Large centrifuge (Hughes lab centrifuge)

-   Multichannel Pipette (300uL)

## **Protocol** {.unnumbered}

### **Before Starting** {.unnumbered}

-   Sample transfer: Samples will be in multiple boxes in freezer, but we only want to take a box out once to minimize sample degradation.
    - We need a sample transfer plan which lists which samples in a given box will be going into which places on the tray
    - Take one box out of the freezer, transfer samples to its appropriate location on the ordered trays.

-   If any precipitate has formed in either the Buffer ATL or Buffer AL, warm solution(s) to 56 degrees C until precipitates have fully dissolved.

-   Preheat thermo-mixer to 56 degrees C.

### **Tissue Lysing** {.unnumbered}

1.  Prep surfaces and area around the scale. First clean with bleach solution, followed by H2O, then 70% EtoH.

2.  Get a styrofoam container with ice to keep tissue samples cool while prepping for extraction. 

3.  Remove one plate of tissue from freezer and let thaw on counter (do not let them sit any longer than necessary). Once thawed they can be placed on ice (this generally won't cause them to re-freeze).

4. Add 18 mL buffer ATL to a 25 mL liquid boat (enough for 100 samples). Add 180uL buffer ATL to each tissue collection tube using the P300 multichannel pipette. Don't pipette to the second stop as it will create too many bubbles. Keep samples covered with tinfoil unless actively pipetting buffer to prevent cross-contamination and minimize pipetting errors.

6.  Tare piece of weighing paper on scale.

7.  Carefully remove tissue from 2mL tube. Use a sterile razor blade to cut a piece of tissue roughly 20mg in weight (cut on weigh boat). Using 95% pure EtoH, gently rinse tissue in weigh boat and pat dry with clean kim wipe, so that the tissue appears nearly dry.

8.  Place tissue on weigh paper and measure the weight. If the tissue weighs 20mg+/-2mg place it in extraction tube. If not, either remove tissue as necessary or add more from sample tissue. Make sure the tissue is pushed all the way down into the solution at the bottom of the tube.

**Note:** Between samples scalpel & forceps should be sterilized by spraying with EtoH and using a flame to burn off any residual EtoH and tissue.

9.  Record weight in lab notebook by well location, **not** by vial ID. Place sample into appropriate collection well plate (cyan plates). Keep plate covered with plastic sheet that has a hole in the center. This hole will expose one well at a time for tissue transfer. Sterilize plastic sheet between samples.

**Note:** Make sure tissue is all the way at the bottom of the well. 

10. Add 2 mL Proteinase K to a 25 mL liquid boat (enough for 100 samples). Once all samples have been cut and placed in collection tubes, pipette 20 uL Proteinase K into each sample tube. 

11.  Seal wells with caps, then place clear cover over rack. Use vortexer to mix samples, then centrifuge for 20-30s at 4500 rpm, ensuring that a counter weight is placed into the centrifuge before starting. (Use practice extraction plate as counter weight.)

12.  Place samples on thermo-mixer set at 56 degrees at 600 rpm (we have plate attachment, but plates are too tall). **BEFORE STARTING THE MIXER**: Make sure all tube caps are securely fastened. In addition, after 2 minutes on the thermo-mixer confirm the tube caps haven't popped open.

13.  Samples can be left for at least 2 hours or overnight to allow for all tissue to be completely lysed.

### **Extraction** {.unnumbered}

1.  Prep surfaces and area around the work bench. First clean with bleach solution, followed by H2O, then 70% EtoH.

2.  After removing samples from the thermomixer, ensure microtubes are properly sealed, cover racks and shake vigorously for 15 seconds. Centrifuge for 30s at 4500 rpm to collect any solution from the caps. Hold down short spin button.

3.  Carefully remove caps and add 410 μl Buffer AL using the 300μL multichannel pipette (split this into two rounds of pipetting 205μl of Buffer AL, only go to the first stop to avoid bubbles). For a full plate of 96 samples, use 45 mL Buffer AL in a 50mL liquid boat. Tightly reseal with new caps.

4.  Place clear cover over the rack and shake vigorously for 15s, then centrifuge 30s at 4500 rpm to collect any solution from the caps. 

**Note:** Ensure ethanol has been added to Buffer AL according to instructions on the container.

5.  Place DNeasy 96 plate on the S-Block, ensuring placement lines up correctly with the sample key.

6.  Carefully remove caps & transfer the lysate (up to 600μl) of each sample to the new wells using the 300μl multichannel pipette (set to 290μl). Pop any bubbles using a  pipette tip.

7.  Seal the plate with an AirPore tape sheet and centrifuge at 4500 rpm for 13 min.

8.  Remove tape and carefully add 500μl of Buffer AW1 to each sample. Use the 300μl multichannel pipette and add 250μl Buffer AW1 twice. This will require ~55mL of buffer AW1 in a liquid boat.

9.  Seal the plate with a new AirPore tape sheet and centrifuge at 4500 rpm for 7 min. 

10.  Remove tape and carefully add 500μl of Buffer AW2 to each sample. Use the 300μl multichannel pipette and add 250μl twice. This will require ~55mL of buffer AW2 in a liquid boat.

11. Seal the plate with a new AirPore tape sheet and centrifuge at 4500 rpm for 20 min. 

**Note:** Spin column membrane should be dry after this step. Spin for an additional 1 min if not.

12.  Transfer the DNeasy 96 plate on a rack of Elution Microtubes RS.

13.  Elute the DNA by adding 200μl of Buffer AE to each sample using the 300μl multichannel pipette. For a full plate, this will require ~20mL of buffer AE. Seal with a new AirPore tape sheet & incubate for 1 min at room temperature (15--25°C). Centrifuge for 3 min at 4500 rpm.

14.  Perform second elution by adding 200μl Buffer AE to each sample using the 300μl multichannel pipette. Incubate for 10 min at room temperature (15--25°C). Centrifuge for 90 seconds at 4500 rpm, and seal elution microtubes with new caps.

15.  Label plate and extracted DNA can be place in "No animals" fridge for a few days, or store at -20 or -80 for long term storage. **AVOID** numerous freeze-thaw cycles.

### **Cleaning the S-Blocks for reuse** {.unnumbered}

from Qiagen:
1. After each use, rinse the S-Blocks thoroughly in tap water
2. Incubate for 1 min at room temperature in 0.4M HCl
3. Wash S-Block thoroughly with distilled water
**Optional:** S-Blocks can be autoclaved after washing, and additional S-Blocks can be ordered from Qiagen

- HCl is located in the corrosives cabinet
    - Concentration: 12.1M
    - To get total volume of 5L of 0.4M HCl: use 165.29mL 12.1M HCl
- Make HCl bath in large red plastic bin
    - Use large plastic graduated cylinder and **add acid to water** not the other way around
- Carefully submerge S-Block for one minute

- Transfer S-Block to another container filled with distilled water
    - Submerge S-Block a few times to rinse
- Over the sink, thoroughly rinse by pouring more distilled water over S-Block
- Dispose of HCl and HCl-contaminated dH20 in large hazardous waste bottle under RNA hood (5L or 1 gal). 


