# Reducing Cognitive Load

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/profdev_ReducingCognitiveLoad.qmd)

------------------------------------------------------------------------

## **Reducing load on ourselves** {.unnumbered}

-   [GTD Getting Things Done](https://hamberg.no/gtd/)

    -   How to organize your lists - see website for details

-   Organize tasks into short term critical, short term not critical, long term less critical, not critical

-   [Declutter your inbox](https://www.fastcompany.com/40507663/the-7-step-guide-to-achieving-inbox-zero-and-staying-there-in-2018)

    -   Archive immediately no action items

    -   Do it if one minute or less

    -   If need more time, set a "snooze" to get it later

    -   Keep emails 5 sentences or less

    -   Make templates

    -   Unsubscribe from all lists or bundle promos

    -   Stop organizing your email

    -   Turn off notifications and create custom notifications for specific people

        -   Only check a few times a day

-   [Art of efficient thinking](https://productivityist.com/efficient-thinking/)

    -   Download your mind

        -   Dictation service, voice recording, copytalk

        -   Idea journal - storage space for ideas - not time sensitive

        -   Google keep - writing things down

        -   Avoid straining your brain by reducing decisions made each day (prepare lunch/clothes day before). Reduce amount of unimportant information.

-   Bullet Journals

    -   Lots of You Tube videos

    -   We discussed whether this would actually reduce cognitive load because it takes so much time

-   [Hacker Noon](https://hackernoon.com/minimizing-the-cognitive-load-in-your-life-bc14f4309fb2)

    -   If something is incomplete, it's in your mind

    -   Slight positive things have a small mental positive effect, while slight negative things have a large negative effect

    -   Read books over articles, avoid newspapers, facebook, etc.

    -   Writing alot reduces cognitive load

    -   "Decision exhaustion" has not held up in replicated studies

    -   `Deep work` and `flow states` - as you do something more often, you need a shorter buildup to the point to become super productive

## **Unsuscribe (Glei)** {.unnumbered}

-   *Negativity bias* (Goleman research)

    -   If we perceive our email as positive, the receiver perceives it as neutral

    -   If we perceive our email as neutral, the receiver perceives it as negative

    -   This happens because of absence of normal social cues

    -   Play close attention to phrasing

-   *Busy bias*

    -   Every email is colored by how busy we are and if we feel we have time for it

    -   10 years ago we spent 0 time on social media because it didn't exist. Now we spend 1.72 hours a day.

    -   Corrosive choice anxiety

-   Map work onto your calendar

    -   Start your day with meaningful work

    -   Daily routine - check email once at noon and once at end of day

        -   *Switching cost* - creative work requires at least 25 minutes to get into the task after an interruption

    -   Outline your goals

    -   Signal to noise - thinking on the decade span instead of the day span "Days are long but the decades are short"

-   *Close the loop* - if you are asking a question, propose an answer

-   Attention to detail:

    -   Compose first, add address later

    -   Any grammatical errors show lack of attention to detail

    -   To remove someone from a chain, bcc them and make sure to mention it in the email

## **Reducing the load we impose on others** {.unnumbered}

-   [Six strategies](http://theelearningcoach.com/learning/reduce-cognitive-load/)

    -   Maintain signal to noise ratio - get rid of all the noise

    -   Promote generative strategies - get learner to interact and generate their own ideas

    -   Write concisely

    -   Supplantive strategies - small steps to bigger problem/tasks

    -   Collaborative learning - divide cognitive process across several individuals

    -   Provide cognitive aids - lists, tools, strategies to offload task complexity

        -   Mindmap on kumu.com

-   [Use F-pattern emails](https://blog.bananatag.com/internal-comms/cognitive-load-impact-on-internal-emails)

    -   5-second test - can someone else understand it in 5 sec?

    -   Predictability - email templates

    -   Visible flow - heading organization and white space

    -   Ease of skimming/scanning -

        -   people skim emails in an F pattern - use pointed headings to convey message and short paragraphs

        -   most important information at the top

-   [Write an email with military precision](https://hbr.org/2016/11/how-to-write-email-with-military-precision)

    -   Informative subject line with keywords

        -   What do I want by emailing this person and distill it to one word

    -   Bottom line up front (BLUF)

        -   Most important information at the top

    -   Don't make recipient scroll - keep it short

    -   Use active voice\
