# Professional Development Resources

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/profdev.qmd)

Hello world!

------------------------------------------------------------------------

## **Collecting data and metadata** {.unnumbered}

-   [How to organize data in spreadsheets](https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html)

-   [Data organization in spreadsheets](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989)

-   [Guide to writing a README file](https://data.research.cornell.edu/content/readme)

## **Time Management** {.unnumbered}

-   [Time Management, Productivity, and Organization](https://docs.google.com/document/d/13xiuKlbF0ao1CSZoeDg5RmtGibtNRclVZeQpAYcLIFo/edit)

## **Discrimination** {.unnumbered}

-   Discrimination is wrong. NU has guidelines for [reporting discrimination](https://www.northeastern.edu/ouec/reporting-options/discrimination/)

-   See the related page for [Title IX offenses](https://www.northeastern.edu/ouec/reporting-options/titleix-prohibited-offenses/)

## **Microaggresion** {.unnumbered}

-   [Recognizing and addressing microaggression](https://github.com/DrK-Lo/lotterhoslabprotocols/blob/23fad2ce227a603e8d3bc604bd203538ea84cbb5/img/RecognizingandAddressingMicroaggressionsTakewaways2021.pdf)

## **Reviewing manuscripts and writing rejections** {.unnumbered}

-   [Lab discussion 2020](https://docs.google.com/document/d/1BGYn66Q0mkXOwL5S_woHOLh7__dTHQzQDxRc5EnKLNw/edit#)

## **Statistics** {.unnumbered}

-   [2020 Lab discussion how to mix mode](https://docs.google.com/document/d/1jQZkbZbZuWnElYmLUntg5qgh1NG2-yAbsT3zzvmbkZ0/edit#heading=h.btb80w3ha1pf)

## **Grant writing** {.unnumbered}

-   [2020 phrasebank and advice](https://docs.google.com/document/d/10TXWztCiID1-wNTGZ37rvYoIVHbf2kWmQMHoqN6pHQk/edit?pli=1)

## **How to start a collaboration and keep it going** {.unnumbered}

-   [2020 lab discussion](https://docs.google.com/document/d/1mgWle41KPHnlCevE5IB9S1AaWQcYDFm_7riQU7WTfOM/edit)

## **Tips for aksing for extensions** {.unnumbered}

-   [Tips for aksing for extensions](https://docs.google.com/document/d/1o87Ua79CeVIQstDpy9m9DtGsZTL9ttFmVB-Kqus1Iig/edit)

## **Errors and mistakes** {.unnumbered}

-   Publishing a correction because of a mistake: [On finding errors in one's published papers](https://dynamicecology.wordpress.com/2016/12/02/on-finding-errors-in-ones-published-analyses/)

-   Publishing a retraction because of a mistake: [Wrong alot?](http://ecoevoevoeco.blogspot.com/2016/12/wrong-lot.html%20http://ecoevoevoeco.blogspot.com/2016/12/wrong-lot.html)

-   Publishing a retraction because of what appears to be fraud: [#PruittGate](https://laskowskilab.faculty.ucdavis.edu/2020/01/29/retractions/)

-   Katie's overview of her career mistakes (need to add link to presentation)

## **Interviewing** {.unnumbered}

-   [Interview questions for a graduate or postdoc application](https://docs.google.com/document/d/1SM3PiIfo4f_Pd_NZxC4Br1g5E0mnqCUlwilrleatNWA/edit)

-   [Interview for a faculty position](https://docs.google.com/document/d/1OvvB6yl_5l05dUn3frL5GEJeksc5xjy8a_keq8sp0fc/edit)

## **Skimming a paper** {.unnumbered}

-   [How to skim a paper](https://docs.google.com/document/d/17wIUVwRGpfRMG-riBjCj9EyCnPMb-K8RX7ww5C0kzf8/edit)

## **Lotterhos Lab notebook discussion** {.unnumbered}

-   [Lotterhos Lab notebook discussion](https://drive.google.com/file/d/1HIVVvMbaF8XW0Jxyh708EYBTegkneJ_C/view?usp=sharing)

## **How to write about mixed models** {.unnumbered}

-   [How to write about mixed models](https://docs.google.com/document/d/1jQZkbZbZuWnElYmLUntg5qgh1NG2-yAbsT3zzvmbkZ0/edit#heading=h.btb80w3ha1pf)

## **Anxiety** {.unnumbered}

We all suffer from anxiety sometimes.

-   NU resources for confidential support and guidance for students can be found through:

    -   [University Health and Counseling Services](https://www.northeastern.edu/uhcs/)

    -   [The Northeastern Center for Spirituality, Dialogue, and Service](https://www.northeastern.edu/spirituallife/)

    -   [the Office of Prevention and Education at Northeastern (OPEN)](https://studentlife.northeastern.edu/open/)

    -   [Office of Institutional Diversity and Inclusion](https://provost.northeastern.edu/oidi/)

    -   Northeastern has added Find\@Northeastern, which is a 24/7 mental health consulting line and can be reached at 1-877-223-9477

    -   In addition, there are graduate student support groups

-   NU resources for staff

    -   To do, but also good benefits here and free services

-   *Anxiety relief for kids* has techniques designed for kids, but I found really helpful in my own life

-   This webpage has a good overview of [cognitive distortions](https://positivepsychology.com/cognitive-distortions/) that we all suffer from

### **Nutrition and anxiety** {.unnumbered}

One time I had severe fatigue. My doctor did a vitamin panel and it turned out to be a vitamin D deficiency.

-   [Understanding nutrition, depression and mental illnesses](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2738337/)

-   [Could a vitamin or mineral deficiency be behind your fatigue?](https://www.health.harvard.edu/mind-and-mood/could-a-vitamin-or-mineral-deficiency-be-behind-your-fatigue)

-   [A review of vitamins and minerals for energy, fatigue, and cognition](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7019700/)

-   [Effect of vitamin D3 on self-perceived fatigue](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5207540/)

-   [Types of nutritional deficiencies you can be tested for by your doctor](https://www.myonemedicalsource.com/2020/06/18/nutritional-testing/)

### **Climate grief and Earth optimism** {.unnumbered}

-   [Climate and Mind](https://www.climateandmind.org/)

-   [Earth Optimism](https://earthoptimism.si.edu/resources/educational-resources/)

-   [Faculty resource from American Sociological Association on dealing emotional reactions to climate grief](https://cpb-us-e1.wpmucdn.com/sites.ucsc.edu/dist/1/1169/files/2021/06/When-students-have-powerful-reactions.pdf)

## **Conflicts of interest** {.unnumbered}

-   [Flawed MPA science retracted](https://sustainablefisheries-uw.org/flawed-mpa-science-retracted/)

## **Antiracism** {.unnumbered}

-   [Anti-racist interventions to transform ecology, evolution and conservation biology departments](https://www.nature.com/articles/s41559-021-01522-z)

## **Lab meeting recordings** {.unnumbered}

Please ask Katie for the password to view

-   [June 1 2021](https://northeastern.zoom.us/rec/share/enHUqKE7sr-bq6gpBMBOsu2-vPz3YsobBGADU2wNAgl80B-O9ijm86bx9kxOiboj.nYjVibVUxw51caKb)

-   [Aug 17, 2021 Discussion of organizing data in spreadsheets](https://northeastern.zoom.us/rec/share/8Z6w6mkq-XTPgyDJU_zcLIp0M5U9tTh5rGo5bhlXdIfKR7vbV4bZsA2Nm3rxvbfv.d3krLgGquGjjO5CP)

-   [Aug 24 2021 Discussion of Price Equation (first half of Chap 6 of Rices' Evolutionary Theory](https://northeastern.zoom.us/rec/share/9JS5ZfB-eySzp6VqK24pHh4bNft2uPhd8wLx3b7J2ycq1IQd4hxxt8bvcXs8WfJs.3dgAcoKa9fQZArZR)

-   [Aug 31 2021 Data Viz discussion from the NU specialist](https://northeastern.zoom.us/rec/share/L4GY5DKi6XCi1nf8_RxkzyGyu6NAojZd4nsNsL1WpxiEfNp5qe_PHd5An9ngPANS.49r97rNHCjo5PNSH)

-   [April 4, 2022 Genomics Pipeline Discussion](https://drive.google.com/file/d/1PGqdpTqKoK9ShX6yj6hNiqI7VVO43gOv/view?usp=sharing)

## **Northeastern Travel and Conference Funding for PhDs** {.unnumbered}

-   [MSC Department-Level Funding Application](https://drive.google.com/file/d/1Lb_1kdAgfSQqCOqkyCWnVshKLY8Y7MHT/view?usp=sharing) The MSC grants up to \$300 once per academic year. Intended to supplement advisor funding. Apply at least 30 days before conference.

-   [College of Science Funding Application](https://forms.office.com/pages/responsepage.aspx?id=gcLuqKOqrk2sm5o5i5IV5yDZoNSxGVNDmDTVJk5ayVFURVRETTY1MUZUUDIzNzRHVFRGQkpaWTBZTi4u) The College of Science grants up to \$350 for domestic travel/conference, or \$500 for international travel/conference. It is expected that there is a matching source (PhD Network, department, or advisor). Preference is given for first-time awardees for whom it would be their first national conference. Apply at least 1 month before conference.

-   [PhD Network Funding Application](https://phd.northeastern.edu/network/resources/travelfunding/) The PhD Network grants up to \$500 once per academic year. It is expected that there is a matching source (COS, department, or advisor). Apply at least 2 months before conference.\
