# How to Publish a Paper

[Edit this page](https://github.com/DrK-Lo/lotterhoslabprotocols/edit/main/profdev_How-to-publish-a-paper.qmd)

------------------------------------------------------------------------

The average time it takes to publish a paper after you first submit it for review is 6-9 months. Each round of review takes 1-4 months, each round of revisions take 1-2 months, and then it can take a month or more to get the proofs and approve the final version for publication. Plan accordingly. If I want a paper published in a particular calendar year, I try to get it submitted by March.

[Read this great ariticle with tips from a famous fiction author on how to write a great paper](https://www.nature.com/articles/d41586-019-02918-5)

## **Books that helped me learn how to write** {.unnumbered}

Writing has two facets: building good writing habits and actually putting words together in a way that makes sense to other people. Knowing the difference between *e.g.* and *i.e.* saves your co-authors time explaining it to you. Grammatical errors frustrate reviewers and panelists, and make them skeptical of attention to detail and the quality of the work.

-   Check out this Nature article ["Kick-Start Writing"](https://www.nature.com/articles/d41586-020-00917-5)

## Authorship

On our Professional Development page there is some information on how we use the Vancouver Protocol to determine authorship.

See also [https://www.elsevier.com/researcher/author/policies-and-guidelines/credit-author-statement](https://www.elsevier.com/researcher/author/policies-and-guidelines/credit-author-statement)

### **Building good writing habits** {.unnumbered}

-   Writing Your Dissertation in 15min/day

-   How to Write Alot

### **Putting words together** {.unnumbered}

-   Style: the elements of clarity and grace

-   Funk and White

## **Thinking backwards from a deadline** {.unnumbered}

This timeline assumes you have a full rough draft 3 months before a deadline. Prior to this time, make sure you have a target journal and stay within the word limit as you write.

-   Week -12: Rough draft ready. A rough draft should not be missing many citations, and should have near-final versions of all the figures and tables.

-   Week -9 to -10: Meeting with co-authors to go over current draft of manuscript, approve methods, decide what figures to include, etc. Keep in mind this meeting could take a couple of weeks to get on the books (so should be planned in week -11).

-   Week -8: Full draft ready, with high quality figures. Make sure this draft is formatted for submission (e.g. word counts, figure number, etc.).

-   Week - 6 to 7: Two weeks for comments from co-authors. Continue to improve manuscript while waiting for comments.

-   Week -5: Incorporate comments from co-authors. Plan another meeting with co-authors if needed.

-   Week - 4: Make sure final draft is formatted for submission (e.g. word counts, figure number, etc.)

-   Week -2 to -3: Two weeks for final comments from all co-authors.

-   Week -1: Fine editing, grammar, figure references, bibliography edits. Leave 2-3 hours for submission.

## **Manuscript, Figures, and Supplement** {.unnumbered}

Every manuscript typically has 3 parts that I submit, the text of the manuscript (written collaboratively in google docs), the figures with legends (in latex), and the supplement (in latex). I use LaTex for figures and supplements because it makes them high quality, and is easier to control the size of the figures as they are displayed on the page.

### **Template to kick-start your manuscript in google docs** {.unnumbered}

[Here is a link to a template, with important things to remember about writing](https://docs.google.com/document/d/15FYgxaSEQ6krNOlOq0qHmz0mD2No_tcRdVpG-xG8EXw/edit) \* Having links to relevant documents at the top of the manuscript can be helpful, including a link to the editor letter, response to reviewers, notes and unused text, etc.

-   Google docs offers a platform for collaboration that does not involve emailing each other many versions, which is inefficient. All changes are available immediately to everyone. It also has a good version control system (Click on "All changes saved in Drive"). I use this system to name specific drafts that I may want to go back to.

    -   Use "Outlines". Labeling different sections with headers and sub-headers will automatically create an outline. "View ---\> Show Document Outline" can make it fast to navigate.

-   Have a separate document for notes, logs, deleted text, and posting old versions of the figures or trial versions of figures.

-   Make sure to use text to create tables, because typesetters will not be happy if you create images or LaTeX tables

-   I like to have a shared folder with pdfs of all the references

-   Have a target journal and stay within the word limit as you write.

### **Make figures high resolution for submission with Latex** {.unnumbered}

-   A good way to frustrate reviewers is to submit high resolution figures in an online system that appends them to the end of your manuscript with no Figure ID or legend.

-   To make my reviewer's life easier, I use LaTeX to create on figures document with figure legends on the same page as the figures. When the final (final) document is accepted for publication, then I just upload the high resolution figures. [Template](https://drive.google.com/drive/folders/1mbvkizpPnM4CjkTTj2ARENtEqDwhXYDU?usp=sharing)

-   It will be important to double check that the Figure Legends in the Manuscript match the Figure Legends in the LaTeX document

### **Make high quality Supplemental Materials with Latex** {.unnumbered}

-   I use the same LaTex template to produce high-quality Supplementary Materials. [Template](https://drive.google.com/drive/folders/1mbvkizpPnM4CjkTTj2ARENtEqDwhXYDU?usp=sharing)

## **Inform all authors of the authorship policy** {.unnumbered}

-   I use the [ICMJE Vancouver Protocol](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html). It is important to run this by all authors at the beginning of a collaboration, and again at publication.

## **Using Paperpile with Google Docs** {.unnumbered}

-   Addons --\> Get add ons --\> search for Paperpile

-   It works best when you search for the webpage or the title of the paper.

-   This system is more efficient than keeping EndNote on your computer, where you have to download the citation and then add it to EndNote to cite it in a word processor.

-   At the bottom of the app is an "Open Paperpile" link, which provides some extra functionality

-   To add all your citations in a document to Paperpile, you can click on a reference in the Bibliography, click "Open", then click on "View all references from this Document", then in the upper right hand corner click on the icon and "Add all references to my library"

## **Write as you go** {.unnumbered}

-   Set aside 15 minutes first thing every morning to engage with the manuscript.

-   Create an outline (through discussions with all authors) and *stick to it*

-   Start with methods, and be sure to update them every time you do the actual method. It is important to be as specific as possible (e.g. kit manufacturer, name of the piece of equipment you used) to ensure the results are reproducible.

-   A well-framed research question should allow you to write the introduction before the results are known. In the Introduction you should lay out the rationale for the study, including the questions or hypotheses to be addressed.

-   I find it helpful to draw text from the papers I am citing or reading if I get stuck in a writing block, and then going back to edit it later.

-   As you start to work on a section, the most important thing is to maintain communication and discussions with all authors, especially if what you write strays from the outline. You may be wasting effort and taking the manuscript in a direction that is different from what others envision.

-   Adding comments to sections that you are working on and how you plan to improve them, or questions you have on how to improve them, can help co-authors understand where your thought process is.

## **Make figures perfect** {.unnumbered}

-   Every detail matters. Be prepared to spend 4-8 hours or more refining a figure, even after you get a general figure that everyone agrees on.

Common mistakes:

-   All axes labels are centered. There are no redundant axis labels in multi-panel plots.

-   y-axis tick labels are not sideways

-   The color pattern works in B&W and for color blind. There are color-blind palettes in R, and there are websites online where you can see how your figure works for a color blind person.

-   No 3-D plots.

-   y-axis scale does not accentuate differences in the effect size (in other words not zoomed in)

-   Base R plotting options:

    -   `bty = "l"` box type is "L" shaped and not a square outline

    -   `las = 1` y-axis tick labels are upright

## **After you get a semi-complete draft** {.unnumbered}

-   Share the google doc with co-authors and colleagues for feedback. It can take a couple weeks to get it back from them, and don't be afraid to follow up if they are taking too long. After that it can take a few or several weeks to make edits and changes. While you are waiting on them, you can work on some of the points below.

## **Getting to the final draft** {.unnumbered}

The final stages prior to submission can take about a month or more.

-   I like to go through all the references in my folder and skim them over again. As I read them over, I double check that they are cited correctly, and often I find other places to cite them, which helps to weave common threads throughout. Especially if I am first author, I want to be familiar with the papers that others cited but I haven't read before. This process takes me a couple weeks of 4-5 hours per day.

-   Write your letter to the editor. [Template](https://docs.google.com/document/d/1ye4hs0gYP4l4m27o9V_nPZqXD-EPNBrm9UWj-vBv_Zw/edit)

-   Check the author guidelines for the journal you are submitting to and make sure all sections of the manuscript fit those guidelines.

-   In the "Data Accessibility" section I often put "All datasets and scripts used to create results will be archived on Dryad upon final acceptance of the manuscript. Scripts can currently be seen at the github site XXXX." (Beware if double blind review, you may not want to put the github site)

-   Do not count on co-authors to find mistakes and grammatical errors. I have read over manuscripts 10+ times and there are still errors.

-   Edit for unneccessary words or long sentences.

-   Attention to detail is paramount. Every error that a reviewer finds is a mental check that other important details may have been overlooked in the research.

-   **Writing Author Contributions.** Communication here is paramount. It can help to send this list to each author and let them tell you where they think they should have their initials by.
See also [https://www.elsevier.com/researcher/author/policies-and-guidelines/credit-author-statement](https://www.elsevier.com/researcher/author/policies-and-guidelines/credit-author-statement)
Who:

    -   Conceptualized and administered the project,

    -   Obtained funding

    -   Developed methods

    -   Collected data

    -   Did the formal analysis

    -   Visualized the data

    -   Wrote the software

    -   Performed data curation

    -   Wrote the original draft of the manuscript

    -   All authors reviewed and edited the manuscript.

-   Be sure to have page and line numbers. There is an "Line Numbers for Google Docs Add On"

-   Edit all references in the Bibliography (this is the very last thing you do). Paperpile often has errors, especially with capitalization. You do not want to have a reviewer find their name was spelled wrong in your reference list, so check also for special characters. Species italics is another thing that often needs to be edited.

## **Submitting the manuscript** {.unnumbered}

-   Prior to submission, get final approval (in writing) from all authors and agreement that all authors are accountable for mistakes or errors per ICJMES policy.

-   When I first started submitting manuscripts, I had to go through multiple attempts because I kept making edits or changes to the manuscript. Just wait until everything is perfect and do it once.

- I like to submit the figures and their legends together in the word doc at the end, where reviewers can find them. I will also submit the pdfs of the figures seperately if they want to see the high quality versions.

-   After you submit, name your draft in google drive. (Click on "All changes saved in Drive"). Save the draft as a Word Document, which will be used below if a "track changes" document is needed in the response to reviews.

## **Responding to reviews** {.unnumbered}

-   Your baseline expectation should be a rejection with extensive comments from reviewers.

-   Involve all authors in responding to reviews, communication is important here. Take every review seriously, even if they are being ridiculous. A good editor will emphasize the good reviews and de-emphasize the ridiculous ones.

-   Be respectful when responding to reviews, and be sure to note which comments were helpful. Also be sure to note where there is disagreement among reviewers when responding to comments.

-   Be sure to acknowledge the Editor and anonymous reviewers in your "Acknowledgments" section

-   It is good to submit a "track changes" document. Microsoft word has a great system for comparing 2 documents. After all authors approve the final revisions with all changes accepted, export the manuscript to .docx. In Word, go to "Tools --\> Track Changes --\> Compare Documents". Upload the draft that was submitted the first time around. Word will produce a document showing all changes between the two documents, which you can submit with your review.

## Katie's step by step for responding to reviews


1. Read them
2. Wait 2 days
3. Schedule regular meetings with your co-authors to develop consensus on how to respond to comments
4. Create a folder for the response to reviews. This folder will hold the edited figure files, compared documents, manuscript and new cover letter. I like to number my figures “F1” “F2” etc. I like to name my folder “YYYYMMDD JournalName Revisions”
5. Make sure to save the first version as a word file before you start. This will be used for compare documents.
6. To avoid cognitive load of multiple documents, I work in one Google Doc with Sections (Reviewer comment, letter to editor, title page, manuscript, etc). Set each section to start on it’s own page numbering and line numbering.
7. Copy the whole shebang including the editor’s decision and paste it into reviewer comments section of the google doc
8. Put all the reviewer comments as comments at the relevant line numbers in the manuscript - don’t make any edits yet or you will screw up the line numbers! Draft responses as you do this and number the responses.
9. As you make edits, you can track changes and accept them as needed to keep the document clean. You will use “compare docs” in Word at the end to show the editor where the revisions are made, so you don’t have to work in a messy manuscript now.
10. For each response that is more than a minor edit, make sure to copy the edited text in the main document. This step is important because it lowers the cognitive load for editors and reviewers, who will not need to scour the document to understand your edits. You do not need to cite the new line numbers for your revisions, just cite the section and paste in the new text. Examples:
    * L22-24. “Although genomic forecasting methods are becoming more accessible, evaluating their limitations in a particular study system requires careful planning and experimentation. Meticulously designed evaluation experiments can reveal the limitations of forecasts” These two sentences are repetitive. 
    * Response 8: The second sentence was edited to state: “Meticulously designed evaluation experiments can clarify the robustness of the forecasts for application in management”
    * L62 and L69. I'm a bit uncomfortable with the use of the term “ground-truth measures of fitness” because, as well explained in Element 2, fitness can only be estimated or approximated with proxies. Therefore, I would use instead either “ground-truth data” or “fitness proxies based on ground-truth data”.
    * Response 22: This point is well received. This section now reads (edits underlined): “However, only a few of these studies have actually evaluated those forecasts in experiments with ground-truth data(Exposito-Alonso et al., 2019; Fitzpatrick et al., 2021; Gain et al., 2023; Lind et al., 2024; Rhoné et al., 2020). The definition of ground-truth data is data that is known to be real or true, provided by direct and accurate measurement (in situ). Within the field of genomic forecasting, the ground-truth data should estimate the fitness in a specific environment or a fitness offset between two environments. Fitness can be estimated from the product of viability (survival) and fecundity(Conner & Hartl, 2004), but these can be difficult to measure. Instead, proxies of fitness such as growth rate or size are often used as ground-truth data (see Element 2 for discussion). For a study to qualify as a ground-truth experiment, the genomic forecasts are evaluated against ground-truth proxies of fitness collected from multiple individuals or populations in one or more common garden environments.”
11. For majorly revised figures show the old version and the new version in the responses. This step is important because it lowers the cognitive load for editors and reviewers, who will not need to scour the document to see the new version.
12. Use kind language for constructive comments, e.g. “We agreed”, “we thank the reviewer”, “express our appreciation”, “this is a good suggestion”, “this point is well received”, etc. 
13. Re-read the entire manuscript from start to finish
14. Once co-authors sign off, accept all the edits, delete all the comments, and output to a word file. Use “compare documents” in Word to get all the changes from the first version. 
15. Keep the figures with their legends at the end of the document where reviewers can find them. I also upload the high-quality pdfs of figures for review.
16. Make sure to thank the editor and reviewers in the Acknowledgements section

Example doc: https://docs.google.com/document/d/1yTJnATJFoVoqvROZ4vOJeEPbnmybR0cyCgKrKCLbblM/edit#heading=h.jj7mh0obo2p6 Ask Katie for access


## **The final acceptance** {.unnumbered}

-   **Archiving data and scripts on Dryad.** Ensure that the scripts are still reproducible by running them on your computer and someone else's. Once you upload to Dryad, that's it - you can't go back and edit or change something.

    -   Dryad has specific instructions for compressing and transferring large files, so initiate communication with them before you start this process. Make sure everything is perfect, then compress the folder with all data and scripts per Dryad instructions.

    -   The process of getting a DOI can take about a week. After you get the DOI, add the data citation to your Bibliography per Dryad instructions.

## **Proofs** {.unnumbered}

-   When you receive the proofs, you typically have 48 hours to make corrections and send them back. It is good to share with co-authors if they have the time, but typically it is up to the first author to make corrections.

-   Read through the entire proofs, and don't just focus on the questions from the typesetters. There will still be mistakes and grammatical errors to be found.

## **Publication** {.unnumbered}

-   Celebrate!
