# Purchasing

Any purchases made with grant funds above \$10K need to be routed through the University's procurement department. To be ahead of the process, make sure you have at least 3 quotes from different vendors for each \>\$10K purchase.

------------------------------------------------------------------------

## **Purchases under \$10K:** {.unnumbered}

**Amazon Business Account:**

-   Search and make purchases like you normally do through Amazon (billing and shipping address should be already saved in the account settings).

-   Print order to pdf and save it using the file name format below, then place the pdf file into the folder Order and Receipts (located in Google Drive, LotLab_Shared_Resources)

**Northeastern My Marketplace:**

-   Fill out and submit your [Access Form](https://github.com/thais-neu/Thais_lab_protocols/files/7541425/myMarketplace-Access-Form.pdf) to gain access and purchase through My Marketplace.

-   Log in to your MyNortheastern portal, go to Services and Links, under Finance Serces for Faculty & Staff, select myMarketplace.

-   Save myMarketplace to you favorites so it's easier to find next time.

-   We typically look through the Fisher Scientific catalog first - using key works or product/catalog number.

-   Add your items to cart; when done shopping, click on the cart (view cart) and then on "Return Carto to Purchasing Application" and then "Submit".

-   On the next page, double-check Shipping Information and select:

    -   Index to charge from (Ask Katie if not sure),

    -   Account code: 'Scientific Supplies',

    -   Click "Send to Approval",

    -   Print that page (or the order confirmation you should receive by email) to a pdf and save it to Orders and Receipts using the format below for file name.

**Save orders/invoces to a pdf file and into the folder 'Orders and Receipts' using the following file name:**

YYYYMMDD_Amazon_whatpurchase.pdf

-   example: 20210602_Amazon_labnotebooks.pdf

-   example: 20211115_Marketplace_dissectingscissors.pdf
